// @generated by protoc-gen-es v2.13.0 with parameter "target=ts,import_extension=none"
// @generated from file config.proto (package crossme, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file config.proto.
 */
export const file_config: GenFile = /*@__PURE__*/
  fileDesc("Cgxjb25maWcucHJvdG8SB2Nyb3NzbWUiIAoGQ29uZmlnEhYKDnNjaGVtYV92ZXJzaW9uGAEgASgFQhRaEmNyb3NzbWUuYXBwL3NyYy9wYmIGcHJvdG8z");

/**
 * @generated from message crossme.Config
 */
export type Config = Message<"crossme.Config"> & {
  /**
   * @generated from field: int32 schema_version = 1;
   */
  schemaVersion: number;
};

/**
 * Describes the message crossme.Config.
 * Use `create(ConfigSchema)` to create a new message.
 */
export const ConfigSchema: GenMessage<Config> = /*@__PURE__*/
  messageDesc(file_config, 0);

