/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var puzzle_pb = require('./puzzle_pb.js');
var fill_pb = require('./fill_pb.js');
goog.exportSymbol('proto.crossme.GetPuzzleByIdArgs', null, global);
goog.exportSymbol('proto.crossme.GetPuzzleIndexArgs', null, global);
goog.exportSymbol('proto.crossme.GetPuzzleIndexResponse', null, global);
goog.exportSymbol('proto.crossme.GetPuzzleResponse', null, global);
goog.exportSymbol('proto.crossme.InteractEvent', null, global);
goog.exportSymbol('proto.crossme.InteractEvent.FillChanged', null, global);
goog.exportSymbol('proto.crossme.InteractEvent.Initialize', null, global);
goog.exportSymbol('proto.crossme.InteractResponse', null, global);
goog.exportSymbol('proto.crossme.UploadPuzzleArgs', null, global);
goog.exportSymbol('proto.crossme.UploadPuzzleResponse', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.crossme.GetPuzzleIndexArgs = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.crossme.GetPuzzleIndexArgs, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.crossme.GetPuzzleIndexArgs.displayName = 'proto.crossme.GetPuzzleIndexArgs';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.crossme.GetPuzzleIndexArgs.prototype.toObject = function(opt_includeInstance) {
  return proto.crossme.GetPuzzleIndexArgs.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.crossme.GetPuzzleIndexArgs} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.crossme.GetPuzzleIndexArgs.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.crossme.GetPuzzleIndexArgs}
 */
proto.crossme.GetPuzzleIndexArgs.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.crossme.GetPuzzleIndexArgs;
  return proto.crossme.GetPuzzleIndexArgs.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.crossme.GetPuzzleIndexArgs} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.crossme.GetPuzzleIndexArgs}
 */
proto.crossme.GetPuzzleIndexArgs.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.crossme.GetPuzzleIndexArgs.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.crossme.GetPuzzleIndexArgs.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.crossme.GetPuzzleIndexArgs} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.crossme.GetPuzzleIndexArgs.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.crossme.GetPuzzleIndexResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.crossme.GetPuzzleIndexResponse.repeatedFields_, null);
};
goog.inherits(proto.crossme.GetPuzzleIndexResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.crossme.GetPuzzleIndexResponse.displayName = 'proto.crossme.GetPuzzleIndexResponse';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.crossme.GetPuzzleIndexResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.crossme.GetPuzzleIndexResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.crossme.GetPuzzleIndexResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.crossme.GetPuzzleIndexResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.crossme.GetPuzzleIndexResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    puzzlesList: jspb.Message.toObjectList(msg.getPuzzlesList(),
    puzzle_pb.PuzzleIndex.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.crossme.GetPuzzleIndexResponse}
 */
proto.crossme.GetPuzzleIndexResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.crossme.GetPuzzleIndexResponse;
  return proto.crossme.GetPuzzleIndexResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.crossme.GetPuzzleIndexResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.crossme.GetPuzzleIndexResponse}
 */
proto.crossme.GetPuzzleIndexResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new puzzle_pb.PuzzleIndex;
      reader.readMessage(value,puzzle_pb.PuzzleIndex.deserializeBinaryFromReader);
      msg.addPuzzles(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.crossme.GetPuzzleIndexResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.crossme.GetPuzzleIndexResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.crossme.GetPuzzleIndexResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.crossme.GetPuzzleIndexResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPuzzlesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      puzzle_pb.PuzzleIndex.serializeBinaryToWriter
    );
  }
};


/**
 * repeated PuzzleIndex puzzles = 1;
 * @return {!Array<!proto.crossme.PuzzleIndex>}
 */
proto.crossme.GetPuzzleIndexResponse.prototype.getPuzzlesList = function() {
  return /** @type{!Array<!proto.crossme.PuzzleIndex>} */ (
    jspb.Message.getRepeatedWrapperField(this, puzzle_pb.PuzzleIndex, 1));
};


/** @param {!Array<!proto.crossme.PuzzleIndex>} value */
proto.crossme.GetPuzzleIndexResponse.prototype.setPuzzlesList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.crossme.PuzzleIndex=} opt_value
 * @param {number=} opt_index
 * @return {!proto.crossme.PuzzleIndex}
 */
proto.crossme.GetPuzzleIndexResponse.prototype.addPuzzles = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.crossme.PuzzleIndex, opt_index);
};


proto.crossme.GetPuzzleIndexResponse.prototype.clearPuzzlesList = function() {
  this.setPuzzlesList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.crossme.GetPuzzleByIdArgs = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.crossme.GetPuzzleByIdArgs, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.crossme.GetPuzzleByIdArgs.displayName = 'proto.crossme.GetPuzzleByIdArgs';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.crossme.GetPuzzleByIdArgs.prototype.toObject = function(opt_includeInstance) {
  return proto.crossme.GetPuzzleByIdArgs.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.crossme.GetPuzzleByIdArgs} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.crossme.GetPuzzleByIdArgs.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.crossme.GetPuzzleByIdArgs}
 */
proto.crossme.GetPuzzleByIdArgs.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.crossme.GetPuzzleByIdArgs;
  return proto.crossme.GetPuzzleByIdArgs.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.crossme.GetPuzzleByIdArgs} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.crossme.GetPuzzleByIdArgs}
 */
proto.crossme.GetPuzzleByIdArgs.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.crossme.GetPuzzleByIdArgs.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.crossme.GetPuzzleByIdArgs.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.crossme.GetPuzzleByIdArgs} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.crossme.GetPuzzleByIdArgs.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.crossme.GetPuzzleByIdArgs.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.crossme.GetPuzzleByIdArgs.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.crossme.GetPuzzleResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.crossme.GetPuzzleResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.crossme.GetPuzzleResponse.displayName = 'proto.crossme.GetPuzzleResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.crossme.GetPuzzleResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.crossme.GetPuzzleResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.crossme.GetPuzzleResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.crossme.GetPuzzleResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    puzzle: (f = msg.getPuzzle()) && puzzle_pb.Puzzle.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.crossme.GetPuzzleResponse}
 */
proto.crossme.GetPuzzleResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.crossme.GetPuzzleResponse;
  return proto.crossme.GetPuzzleResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.crossme.GetPuzzleResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.crossme.GetPuzzleResponse}
 */
proto.crossme.GetPuzzleResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new puzzle_pb.Puzzle;
      reader.readMessage(value,puzzle_pb.Puzzle.deserializeBinaryFromReader);
      msg.setPuzzle(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.crossme.GetPuzzleResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.crossme.GetPuzzleResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.crossme.GetPuzzleResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.crossme.GetPuzzleResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPuzzle();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      puzzle_pb.Puzzle.serializeBinaryToWriter
    );
  }
};


/**
 * optional Puzzle puzzle = 1;
 * @return {?proto.crossme.Puzzle}
 */
proto.crossme.GetPuzzleResponse.prototype.getPuzzle = function() {
  return /** @type{?proto.crossme.Puzzle} */ (
    jspb.Message.getWrapperField(this, puzzle_pb.Puzzle, 1));
};


/** @param {?proto.crossme.Puzzle|undefined} value */
proto.crossme.GetPuzzleResponse.prototype.setPuzzle = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.crossme.GetPuzzleResponse.prototype.clearPuzzle = function() {
  this.setPuzzle(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.crossme.GetPuzzleResponse.prototype.hasPuzzle = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.crossme.UploadPuzzleArgs = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.crossme.UploadPuzzleArgs, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.crossme.UploadPuzzleArgs.displayName = 'proto.crossme.UploadPuzzleArgs';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.crossme.UploadPuzzleArgs.prototype.toObject = function(opt_includeInstance) {
  return proto.crossme.UploadPuzzleArgs.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.crossme.UploadPuzzleArgs} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.crossme.UploadPuzzleArgs.toObject = function(includeInstance, msg) {
  var f, obj = {
    filename: jspb.Message.getFieldWithDefault(msg, 1, ""),
    data: msg.getData_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.crossme.UploadPuzzleArgs}
 */
proto.crossme.UploadPuzzleArgs.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.crossme.UploadPuzzleArgs;
  return proto.crossme.UploadPuzzleArgs.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.crossme.UploadPuzzleArgs} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.crossme.UploadPuzzleArgs}
 */
proto.crossme.UploadPuzzleArgs.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setFilename(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.crossme.UploadPuzzleArgs.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.crossme.UploadPuzzleArgs.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.crossme.UploadPuzzleArgs} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.crossme.UploadPuzzleArgs.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFilename();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getData_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
};


/**
 * optional string filename = 1;
 * @return {string}
 */
proto.crossme.UploadPuzzleArgs.prototype.getFilename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.crossme.UploadPuzzleArgs.prototype.setFilename = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional bytes data = 2;
 * @return {string}
 */
proto.crossme.UploadPuzzleArgs.prototype.getData = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes data = 2;
 * This is a type-conversion wrapper around `getData()`
 * @return {string}
 */
proto.crossme.UploadPuzzleArgs.prototype.getData_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getData()));
};


/**
 * optional bytes data = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getData()`
 * @return {!Uint8Array}
 */
proto.crossme.UploadPuzzleArgs.prototype.getData_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getData()));
};


/** @param {!(string|Uint8Array)} value */
proto.crossme.UploadPuzzleArgs.prototype.setData = function(value) {
  jspb.Message.setProto3BytesField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.crossme.UploadPuzzleResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.crossme.UploadPuzzleResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.crossme.UploadPuzzleResponse.displayName = 'proto.crossme.UploadPuzzleResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.crossme.UploadPuzzleResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.crossme.UploadPuzzleResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.crossme.UploadPuzzleResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.crossme.UploadPuzzleResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    puzzle: (f = msg.getPuzzle()) && puzzle_pb.Puzzle.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.crossme.UploadPuzzleResponse}
 */
proto.crossme.UploadPuzzleResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.crossme.UploadPuzzleResponse;
  return proto.crossme.UploadPuzzleResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.crossme.UploadPuzzleResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.crossme.UploadPuzzleResponse}
 */
proto.crossme.UploadPuzzleResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new puzzle_pb.Puzzle;
      reader.readMessage(value,puzzle_pb.Puzzle.deserializeBinaryFromReader);
      msg.setPuzzle(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.crossme.UploadPuzzleResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.crossme.UploadPuzzleResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.crossme.UploadPuzzleResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.crossme.UploadPuzzleResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPuzzle();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      puzzle_pb.Puzzle.serializeBinaryToWriter
    );
  }
};


/**
 * optional Puzzle puzzle = 1;
 * @return {?proto.crossme.Puzzle}
 */
proto.crossme.UploadPuzzleResponse.prototype.getPuzzle = function() {
  return /** @type{?proto.crossme.Puzzle} */ (
    jspb.Message.getWrapperField(this, puzzle_pb.Puzzle, 1));
};


/** @param {?proto.crossme.Puzzle|undefined} value */
proto.crossme.UploadPuzzleResponse.prototype.setPuzzle = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.crossme.UploadPuzzleResponse.prototype.clearPuzzle = function() {
  this.setPuzzle(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.crossme.UploadPuzzleResponse.prototype.hasPuzzle = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.crossme.InteractEvent = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.crossme.InteractEvent.oneofGroups_);
};
goog.inherits(proto.crossme.InteractEvent, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.crossme.InteractEvent.displayName = 'proto.crossme.InteractEvent';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.crossme.InteractEvent.oneofGroups_ = [[1,2]];

/**
 * @enum {number}
 */
proto.crossme.InteractEvent.EventCase = {
  EVENT_NOT_SET: 0,
  INITIALIZE: 1,
  FILL_CHANGED: 2
};

/**
 * @return {proto.crossme.InteractEvent.EventCase}
 */
proto.crossme.InteractEvent.prototype.getEventCase = function() {
  return /** @type {proto.crossme.InteractEvent.EventCase} */(jspb.Message.computeOneofCase(this, proto.crossme.InteractEvent.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.crossme.InteractEvent.prototype.toObject = function(opt_includeInstance) {
  return proto.crossme.InteractEvent.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.crossme.InteractEvent} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.crossme.InteractEvent.toObject = function(includeInstance, msg) {
  var f, obj = {
    initialize: (f = msg.getInitialize()) && proto.crossme.InteractEvent.Initialize.toObject(includeInstance, f),
    fillChanged: (f = msg.getFillChanged()) && proto.crossme.InteractEvent.FillChanged.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.crossme.InteractEvent}
 */
proto.crossme.InteractEvent.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.crossme.InteractEvent;
  return proto.crossme.InteractEvent.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.crossme.InteractEvent} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.crossme.InteractEvent}
 */
proto.crossme.InteractEvent.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.crossme.InteractEvent.Initialize;
      reader.readMessage(value,proto.crossme.InteractEvent.Initialize.deserializeBinaryFromReader);
      msg.setInitialize(value);
      break;
    case 2:
      var value = new proto.crossme.InteractEvent.FillChanged;
      reader.readMessage(value,proto.crossme.InteractEvent.FillChanged.deserializeBinaryFromReader);
      msg.setFillChanged(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.crossme.InteractEvent.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.crossme.InteractEvent.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.crossme.InteractEvent} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.crossme.InteractEvent.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInitialize();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.crossme.InteractEvent.Initialize.serializeBinaryToWriter
    );
  }
  f = message.getFillChanged();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.crossme.InteractEvent.FillChanged.serializeBinaryToWriter
    );
  }
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.crossme.InteractEvent.Initialize = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.crossme.InteractEvent.Initialize, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.crossme.InteractEvent.Initialize.displayName = 'proto.crossme.InteractEvent.Initialize';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.crossme.InteractEvent.Initialize.prototype.toObject = function(opt_includeInstance) {
  return proto.crossme.InteractEvent.Initialize.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.crossme.InteractEvent.Initialize} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.crossme.InteractEvent.Initialize.toObject = function(includeInstance, msg) {
  var f, obj = {
    puzzleId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    nodeId: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.crossme.InteractEvent.Initialize}
 */
proto.crossme.InteractEvent.Initialize.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.crossme.InteractEvent.Initialize;
  return proto.crossme.InteractEvent.Initialize.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.crossme.InteractEvent.Initialize} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.crossme.InteractEvent.Initialize}
 */
proto.crossme.InteractEvent.Initialize.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPuzzleId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setNodeId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.crossme.InteractEvent.Initialize.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.crossme.InteractEvent.Initialize.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.crossme.InteractEvent.Initialize} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.crossme.InteractEvent.Initialize.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPuzzleId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getNodeId();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string puzzle_id = 1;
 * @return {string}
 */
proto.crossme.InteractEvent.Initialize.prototype.getPuzzleId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.crossme.InteractEvent.Initialize.prototype.setPuzzleId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string node_id = 2;
 * @return {string}
 */
proto.crossme.InteractEvent.Initialize.prototype.getNodeId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.crossme.InteractEvent.Initialize.prototype.setNodeId = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.crossme.InteractEvent.FillChanged = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.crossme.InteractEvent.FillChanged, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.crossme.InteractEvent.FillChanged.displayName = 'proto.crossme.InteractEvent.FillChanged';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.crossme.InteractEvent.FillChanged.prototype.toObject = function(opt_includeInstance) {
  return proto.crossme.InteractEvent.FillChanged.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.crossme.InteractEvent.FillChanged} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.crossme.InteractEvent.FillChanged.toObject = function(includeInstance, msg) {
  var f, obj = {
    fill: (f = msg.getFill()) && fill_pb.Fill.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.crossme.InteractEvent.FillChanged}
 */
proto.crossme.InteractEvent.FillChanged.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.crossme.InteractEvent.FillChanged;
  return proto.crossme.InteractEvent.FillChanged.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.crossme.InteractEvent.FillChanged} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.crossme.InteractEvent.FillChanged}
 */
proto.crossme.InteractEvent.FillChanged.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new fill_pb.Fill;
      reader.readMessage(value,fill_pb.Fill.deserializeBinaryFromReader);
      msg.setFill(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.crossme.InteractEvent.FillChanged.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.crossme.InteractEvent.FillChanged.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.crossme.InteractEvent.FillChanged} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.crossme.InteractEvent.FillChanged.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFill();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      fill_pb.Fill.serializeBinaryToWriter
    );
  }
};


/**
 * optional Fill fill = 1;
 * @return {?proto.crossme.Fill}
 */
proto.crossme.InteractEvent.FillChanged.prototype.getFill = function() {
  return /** @type{?proto.crossme.Fill} */ (
    jspb.Message.getWrapperField(this, fill_pb.Fill, 1));
};


/** @param {?proto.crossme.Fill|undefined} value */
proto.crossme.InteractEvent.FillChanged.prototype.setFill = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.crossme.InteractEvent.FillChanged.prototype.clearFill = function() {
  this.setFill(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.crossme.InteractEvent.FillChanged.prototype.hasFill = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Initialize initialize = 1;
 * @return {?proto.crossme.InteractEvent.Initialize}
 */
proto.crossme.InteractEvent.prototype.getInitialize = function() {
  return /** @type{?proto.crossme.InteractEvent.Initialize} */ (
    jspb.Message.getWrapperField(this, proto.crossme.InteractEvent.Initialize, 1));
};


/** @param {?proto.crossme.InteractEvent.Initialize|undefined} value */
proto.crossme.InteractEvent.prototype.setInitialize = function(value) {
  jspb.Message.setOneofWrapperField(this, 1, proto.crossme.InteractEvent.oneofGroups_[0], value);
};


proto.crossme.InteractEvent.prototype.clearInitialize = function() {
  this.setInitialize(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.crossme.InteractEvent.prototype.hasInitialize = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional FillChanged fill_changed = 2;
 * @return {?proto.crossme.InteractEvent.FillChanged}
 */
proto.crossme.InteractEvent.prototype.getFillChanged = function() {
  return /** @type{?proto.crossme.InteractEvent.FillChanged} */ (
    jspb.Message.getWrapperField(this, proto.crossme.InteractEvent.FillChanged, 2));
};


/** @param {?proto.crossme.InteractEvent.FillChanged|undefined} value */
proto.crossme.InteractEvent.prototype.setFillChanged = function(value) {
  jspb.Message.setOneofWrapperField(this, 2, proto.crossme.InteractEvent.oneofGroups_[0], value);
};


proto.crossme.InteractEvent.prototype.clearFillChanged = function() {
  this.setFillChanged(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.crossme.InteractEvent.prototype.hasFillChanged = function() {
  return jspb.Message.getField(this, 2) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.crossme.InteractResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.crossme.InteractResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.crossme.InteractResponse.displayName = 'proto.crossme.InteractResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.crossme.InteractResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.crossme.InteractResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.crossme.InteractResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.crossme.InteractResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    fill: (f = msg.getFill()) && fill_pb.Fill.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.crossme.InteractResponse}
 */
proto.crossme.InteractResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.crossme.InteractResponse;
  return proto.crossme.InteractResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.crossme.InteractResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.crossme.InteractResponse}
 */
proto.crossme.InteractResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new fill_pb.Fill;
      reader.readMessage(value,fill_pb.Fill.deserializeBinaryFromReader);
      msg.setFill(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.crossme.InteractResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.crossme.InteractResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.crossme.InteractResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.crossme.InteractResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getFill();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      fill_pb.Fill.serializeBinaryToWriter
    );
  }
};


/**
 * optional Fill fill = 1;
 * @return {?proto.crossme.Fill}
 */
proto.crossme.InteractResponse.prototype.getFill = function() {
  return /** @type{?proto.crossme.Fill} */ (
    jspb.Message.getWrapperField(this, fill_pb.Fill, 1));
};


/** @param {?proto.crossme.Fill|undefined} value */
proto.crossme.InteractResponse.prototype.setFill = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.crossme.InteractResponse.prototype.clearFill = function() {
  this.setFill(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.crossme.InteractResponse.prototype.hasFill = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.crossme);
