// @generated by protoc-gen-es v2.13.0 with parameter "target=ts,import_extension=none"
// @generated from file crossme.proto (package crossme, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Puzzle, PuzzleIndex } from "./puzzle_pb";
import { file_puzzle } from "./puzzle_pb";
import type { Fill } from "./fill_pb";
import { file_fill } from "./fill_pb";
import type { Game } from "./game_pb";
import { file_game } from "./game_pb";
import type { User } from "./user_pb";
import { file_user } from "./user_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file crossme.proto.
 */
export const file_crossme: GenFile = /*@__PURE__*/
  fileDesc("Cg1jcm9zc21lLnByb3RvEgdjcm9zc21lIhQKEkdldFB1enpsZUluZGV4QXJncyI/ChZHZXRQdXp6bGVJbmRleFJlc3BvbnNlEiUKB3B1enpsZXMYASADKAsyFC5jcm9zc21lLlB1enpsZUluZGV4Ih8KEUdldFB1enpsZUJ5SWRBcmdzEgoKAmlkGAEgASgJIjQKEUdldFB1enpsZVJlc3BvbnNlEh8KBnB1enpsZRgBIAEoCzIPLmNyb3NzbWUuUHV6emxlIiAKC05ld0dhbWVBcmdzEhEKCXB1enpsZV9pZBgBIAEoCSIuCg9OZXdHYW1lUmVzcG9uc2USGwoEZ2FtZRgBIAEoCzINLmNyb3NzbWUuR2FtZSIdCg9HZXRHYW1lQnlJZEFyZ3MSCgoCaWQYASABKAkiTwoPR2V0R2FtZVJlc3BvbnNlEhsKBGdhbWUYASABKAsyDS5jcm9zc21lLkdhbWUSHwoGcHV6emxlGAIgASgLMg8uY3Jvc3NtZS5QdXp6bGUiMgoQVXBsb2FkUHV6emxlQXJncxIQCghmaWxlbmFtZRgBIAEoCRIMCgRkYXRhGAIgASgMIjcKFFVwbG9hZFB1enpsZVJlc3BvbnNlEh8KBnB1enpsZRgBIAEoCzIPLmNyb3NzbWUuUHV6emxlIjEKDVN1YnNjcmliZUFyZ3MSDwoHZ2FtZV9pZBgBIAEoCRIPCgdub2RlX2lkGAIgASgJIi0KDlN1YnNjcmliZUV2ZW50EhsKBGZpbGwYASABKAsyDS5jcm9zc21lLkZpbGwiTwoOVXBkYXRlRmlsbEFyZ3MSDwoHZ2FtZV9pZBgBIAEoCRIPCgdub2RlX2lkGAIgASgJEhsKBGZpbGwYAyABKAsyDS5jcm9zc21lLkZpbGwiFAoSVXBkYXRlRmlsbFJlc3BvbnNlIg0KC0dldFNlbGZBcmdzIi4KD0dldFNlbGZSZXNwb25zZRIbCgR1c2VyGAEgASgLMg0uY3Jvc3NtZS5Vc2VyMqkECgdDcm9zc01lEk4KDkdldFB1enpsZUluZGV4EhsuY3Jvc3NtZS5HZXRQdXp6bGVJbmRleEFyZ3MaHy5jcm9zc21lLkdldFB1enpsZUluZGV4UmVzcG9uc2USRwoNR2V0UHV6emxlQnlJZBIaLmNyb3NzbWUuR2V0UHV6emxlQnlJZEFyZ3MaGi5jcm9zc21lLkdldFB1enpsZVJlc3BvbnNlEjkKB05ld0dhbWUSFC5jcm9zc21lLk5ld0dhbWVBcmdzGhguY3Jvc3NtZS5OZXdHYW1lUmVzcG9uc2USQQoLR2V0R2FtZUJ5SWQSGC5jcm9zc21lLkdldEdhbWVCeUlkQXJncxoYLmNyb3NzbWUuR2V0R2FtZVJlc3BvbnNlEkgKDFVwbG9hZFB1enpsZRIZLmNyb3NzbWUuVXBsb2FkUHV6emxlQXJncxodLmNyb3NzbWUuVXBsb2FkUHV6emxlUmVzcG9uc2USQgoKVXBkYXRlRmlsbBIXLmNyb3NzbWUuVXBkYXRlRmlsbEFyZ3MaGy5jcm9zc21lLlVwZGF0ZUZpbGxSZXNwb25zZRI+CglTdWJzY3JpYmUSFi5jcm9zc21lLlN1YnNjcmliZUFyZ3MaFy5jcm9zc21lLlN1YnNjcmliZUV2ZW50MAESOQoHR2V0U2VsZhIULmNyb3NzbWUuR2V0U2VsZkFyZ3MaGC5jcm9zc21lLkdldFNlbGZSZXNwb25zZUIUWhJjcm9zc21lLmFwcC9zcmMvcGJiBnByb3RvMw", [file_puzzle, file_fill, file_game, file_user]);

/**
 * @generated from message crossme.GetPuzzleIndexArgs
 */
export type GetPuzzleIndexArgs = Message<"crossme.GetPuzzleIndexArgs"> & {
};

/**
 * Describes the message crossme.GetPuzzleIndexArgs.
 * Use `create(GetPuzzleIndexArgsSchema)` to create a new message.
 */
export const GetPuzzleIndexArgsSchema: GenMessage<GetPuzzleIndexArgs> = /*@__PURE__*/
  messageDesc(file_crossme, 0);

/**
 * @generated from message crossme.GetPuzzleIndexResponse
 */
export type GetPuzzleIndexResponse = Message<"crossme.GetPuzzleIndexResponse"> & {
  /**
   * @generated from field: repeated crossme.PuzzleIndex puzzles = 1;
   */
  puzzles: PuzzleIndex[];
};

/**
 * Describes the message crossme.GetPuzzleIndexResponse.
 * Use `create(GetPuzzleIndexResponseSchema)` to create a new message.
 */
export const GetPuzzleIndexResponseSchema: GenMessage<GetPuzzleIndexResponse> = /*@__PURE__*/
  messageDesc(file_crossme, 1);

/**
 * @generated from message crossme.GetPuzzleByIdArgs
 */
export type GetPuzzleByIdArgs = Message<"crossme.GetPuzzleByIdArgs"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message crossme.GetPuzzleByIdArgs.
 * Use `create(GetPuzzleByIdArgsSchema)` to create a new message.
 */
export const GetPuzzleByIdArgsSchema: GenMessage<GetPuzzleByIdArgs> = /*@__PURE__*/
  messageDesc(file_crossme, 2);

/**
 * @generated from message crossme.GetPuzzleResponse
 */
export type GetPuzzleResponse = Message<"crossme.GetPuzzleResponse"> & {
  /**
   * @generated from field: crossme.Puzzle puzzle = 1;
   */
  puzzle?: Puzzle | undefined;
};

/**
 * Describes the message crossme.GetPuzzleResponse.
 * Use `create(GetPuzzleResponseSchema)` to create a new message.
 */
export const GetPuzzleResponseSchema: GenMessage<GetPuzzleResponse> = /*@__PURE__*/
  messageDesc(file_crossme, 3);

/**
 * @generated from message crossme.NewGameArgs
 */
export type NewGameArgs = Message<"crossme.NewGameArgs"> & {
  /**
   * @generated from field: string puzzle_id = 1;
   */
  puzzleId: string;
};

/**
 * Describes the message crossme.NewGameArgs.
 * Use `create(NewGameArgsSchema)` to create a new message.
 */
export const NewGameArgsSchema: GenMessage<NewGameArgs> = /*@__PURE__*/
  messageDesc(file_crossme, 4);

/**
 * @generated from message crossme.NewGameResponse
 */
export type NewGameResponse = Message<"crossme.NewGameResponse"> & {
  /**
   * @generated from field: crossme.Game game = 1;
   */
  game?: Game | undefined;
};

/**
 * Describes the message crossme.NewGameResponse.
 * Use `create(NewGameResponseSchema)` to create a new message.
 */
export const NewGameResponseSchema: GenMessage<NewGameResponse> = /*@__PURE__*/
  messageDesc(file_crossme, 5);

/**
 * @generated from message crossme.GetGameByIdArgs
 */
export type GetGameByIdArgs = Message<"crossme.GetGameByIdArgs"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message crossme.GetGameByIdArgs.
 * Use `create(GetGameByIdArgsSchema)` to create a new message.
 */
export const GetGameByIdArgsSchema: GenMessage<GetGameByIdArgs> = /*@__PURE__*/
  messageDesc(file_crossme, 6);

/**
 * @generated from message crossme.GetGameResponse
 */
export type GetGameResponse = Message<"crossme.GetGameResponse"> & {
  /**
   * @generated from field: crossme.Game game = 1;
   */
  game?: Game | undefined;

  /**
   * @generated from field: crossme.Puzzle puzzle = 2;
   */
  puzzle?: Puzzle | undefined;
};

/**
 * Describes the message crossme.GetGameResponse.
 * Use `create(GetGameResponseSchema)` to create a new message.
 */
export const GetGameResponseSchema: GenMessage<GetGameResponse> = /*@__PURE__*/
  messageDesc(file_crossme, 7);

/**
 * @generated from message crossme.UploadPuzzleArgs
 */
export type UploadPuzzleArgs = Message<"crossme.UploadPuzzleArgs"> & {
  /**
   * @generated from field: string filename = 1;
   */
  filename: string;

  /**
   * @generated from field: bytes data = 2;
   */
  data: Uint8Array;
};

/**
 * Describes the message crossme.UploadPuzzleArgs.
 * Use `create(UploadPuzzleArgsSchema)` to create a new message.
 */
export const UploadPuzzleArgsSchema: GenMessage<UploadPuzzleArgs> = /*@__PURE__*/
  messageDesc(file_crossme, 8);

/**
 * @generated from message crossme.UploadPuzzleResponse
 */
export type UploadPuzzleResponse = Message<"crossme.UploadPuzzleResponse"> & {
  /**
   * @generated from field: crossme.Puzzle puzzle = 1;
   */
  puzzle?: Puzzle | undefined;
};

/**
 * Describes the message crossme.UploadPuzzleResponse.
 * Use `create(UploadPuzzleResponseSchema)` to create a new message.
 */
export const UploadPuzzleResponseSchema: GenMessage<UploadPuzzleResponse> = /*@__PURE__*/
  messageDesc(file_crossme, 9);

/**
 * @generated from message crossme.SubscribeArgs
 */
export type SubscribeArgs = Message<"crossme.SubscribeArgs"> & {
  /**
   * @generated from field: string game_id = 1;
   */
  gameId: string;

  /**
   * @generated from field: string node_id = 2;
   */
  nodeId: string;
};

/**
 * Describes the message crossme.SubscribeArgs.
 * Use `create(SubscribeArgsSchema)` to create a new message.
 */
export const SubscribeArgsSchema: GenMessage<SubscribeArgs> = /*@__PURE__*/
  messageDesc(file_crossme, 10);

/**
 * @generated from message crossme.SubscribeEvent
 */
export type SubscribeEvent = Message<"crossme.SubscribeEvent"> & {
  /**
   * @generated from field: crossme.Fill fill = 1;
   */
  fill?: Fill | undefined;
};

/**
 * Describes the message crossme.SubscribeEvent.
 * Use `create(SubscribeEventSchema)` to create a new message.
 */
export const SubscribeEventSchema: GenMessage<SubscribeEvent> = /*@__PURE__*/
  messageDesc(file_crossme, 11);

/**
 * @generated from message crossme.UpdateFillArgs
 */
export type UpdateFillArgs = Message<"crossme.UpdateFillArgs"> & {
  /**
   * @generated from field: string game_id = 1;
   */
  gameId: string;

  /**
   * @generated from field: string node_id = 2;
   */
  nodeId: string;

  /**
   * @generated from field: crossme.Fill fill = 3;
   */
  fill?: Fill | undefined;
};

/**
 * Describes the message crossme.UpdateFillArgs.
 * Use `create(UpdateFillArgsSchema)` to create a new message.
 */
export const UpdateFillArgsSchema: GenMessage<UpdateFillArgs> = /*@__PURE__*/
  messageDesc(file_crossme, 12);

/**
 * @generated from message crossme.UpdateFillResponse
 */
export type UpdateFillResponse = Message<"crossme.UpdateFillResponse"> & {
};

/**
 * Describes the message crossme.UpdateFillResponse.
 * Use `create(UpdateFillResponseSchema)` to create a new message.
 */
export const UpdateFillResponseSchema: GenMessage<UpdateFillResponse> = /*@__PURE__*/
  messageDesc(file_crossme, 13);

/**
 * @generated from message crossme.GetSelfArgs
 */
export type GetSelfArgs = Message<"crossme.GetSelfArgs"> & {
};

/**
 * Describes the message crossme.GetSelfArgs.
 * Use `create(GetSelfArgsSchema)` to create a new message.
 */
export const GetSelfArgsSchema: GenMessage<GetSelfArgs> = /*@__PURE__*/
  messageDesc(file_crossme, 14);

/**
 * @generated from message crossme.GetSelfResponse
 */
export type GetSelfResponse = Message<"crossme.GetSelfResponse"> & {
  /**
   * Unset if the request carried no (valid) session: the caller is
   * anonymous.
   *
   * @generated from field: crossme.User user = 1;
   */
  user?: User | undefined;
};

/**
 * Describes the message crossme.GetSelfResponse.
 * Use `create(GetSelfResponseSchema)` to create a new message.
 */
export const GetSelfResponseSchema: GenMessage<GetSelfResponse> = /*@__PURE__*/
  messageDesc(file_crossme, 15);

/**
 * @generated from service crossme.CrossMe
 */
export const CrossMe: GenService<{
  /**
   * @generated from rpc crossme.CrossMe.GetPuzzleIndex
   */
  getPuzzleIndex: {
    methodKind: "unary";
    input: typeof GetPuzzleIndexArgsSchema;
    output: typeof GetPuzzleIndexResponseSchema;
  },
  /**
   * @generated from rpc crossme.CrossMe.GetPuzzleById
   */
  getPuzzleById: {
    methodKind: "unary";
    input: typeof GetPuzzleByIdArgsSchema;
    output: typeof GetPuzzleResponseSchema;
  },
  /**
   * @generated from rpc crossme.CrossMe.NewGame
   */
  newGame: {
    methodKind: "unary";
    input: typeof NewGameArgsSchema;
    output: typeof NewGameResponseSchema;
  },
  /**
   * @generated from rpc crossme.CrossMe.GetGameById
   */
  getGameById: {
    methodKind: "unary";
    input: typeof GetGameByIdArgsSchema;
    output: typeof GetGameResponseSchema;
  },
  /**
   * @generated from rpc crossme.CrossMe.UploadPuzzle
   */
  uploadPuzzle: {
    methodKind: "unary";
    input: typeof UploadPuzzleArgsSchema;
    output: typeof UploadPuzzleResponseSchema;
  },
  /**
   * @generated from rpc crossme.CrossMe.UpdateFill
   */
  updateFill: {
    methodKind: "unary";
    input: typeof UpdateFillArgsSchema;
    output: typeof UpdateFillResponseSchema;
  },
  /**
   * @generated from rpc crossme.CrossMe.Subscribe
   */
  subscribe: {
    methodKind: "server_streaming";
    input: typeof SubscribeArgsSchema;
    output: typeof SubscribeEventSchema;
  },
  /**
   * Who am I? Resolves the caller's session cookie; the session
   * itself is managed by the HTTP endpoints under /api/auth/.
   *
   * @generated from rpc crossme.CrossMe.GetSelf
   */
  getSelf: {
    methodKind: "unary";
    input: typeof GetSelfArgsSchema;
    output: typeof GetSelfResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_crossme, 0);

