/**
 * @fileoverview gRPC-Web generated client stub for crossme
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v2.0.2
// 	protoc              v6.33.1
// source: crossme.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as crossme_pb from './crossme_pb'; // proto import: "crossme.proto"


export class CrossMeClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorGetPuzzleIndex = new grpcWeb.MethodDescriptor(
    '/crossme.CrossMe/GetPuzzleIndex',
    grpcWeb.MethodType.UNARY,
    crossme_pb.GetPuzzleIndexArgs,
    crossme_pb.GetPuzzleIndexResponse,
    (request: crossme_pb.GetPuzzleIndexArgs) => {
      return request.serializeBinary();
    },
    crossme_pb.GetPuzzleIndexResponse.deserializeBinary
  );

  getPuzzleIndex(
    request: crossme_pb.GetPuzzleIndexArgs,
    metadata?: grpcWeb.Metadata | null): Promise<crossme_pb.GetPuzzleIndexResponse>;

  getPuzzleIndex(
    request: crossme_pb.GetPuzzleIndexArgs,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: crossme_pb.GetPuzzleIndexResponse) => void): grpcWeb.ClientReadableStream<crossme_pb.GetPuzzleIndexResponse>;

  getPuzzleIndex(
    request: crossme_pb.GetPuzzleIndexArgs,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: crossme_pb.GetPuzzleIndexResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/crossme.CrossMe/GetPuzzleIndex',
        request,
        metadata || {},
        this.methodDescriptorGetPuzzleIndex,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/crossme.CrossMe/GetPuzzleIndex',
    request,
    metadata || {},
    this.methodDescriptorGetPuzzleIndex);
  }

  methodDescriptorGetPuzzleById = new grpcWeb.MethodDescriptor(
    '/crossme.CrossMe/GetPuzzleById',
    grpcWeb.MethodType.UNARY,
    crossme_pb.GetPuzzleByIdArgs,
    crossme_pb.GetPuzzleResponse,
    (request: crossme_pb.GetPuzzleByIdArgs) => {
      return request.serializeBinary();
    },
    crossme_pb.GetPuzzleResponse.deserializeBinary
  );

  getPuzzleById(
    request: crossme_pb.GetPuzzleByIdArgs,
    metadata?: grpcWeb.Metadata | null): Promise<crossme_pb.GetPuzzleResponse>;

  getPuzzleById(
    request: crossme_pb.GetPuzzleByIdArgs,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: crossme_pb.GetPuzzleResponse) => void): grpcWeb.ClientReadableStream<crossme_pb.GetPuzzleResponse>;

  getPuzzleById(
    request: crossme_pb.GetPuzzleByIdArgs,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: crossme_pb.GetPuzzleResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/crossme.CrossMe/GetPuzzleById',
        request,
        metadata || {},
        this.methodDescriptorGetPuzzleById,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/crossme.CrossMe/GetPuzzleById',
    request,
    metadata || {},
    this.methodDescriptorGetPuzzleById);
  }

  methodDescriptorNewGame = new grpcWeb.MethodDescriptor(
    '/crossme.CrossMe/NewGame',
    grpcWeb.MethodType.UNARY,
    crossme_pb.NewGameArgs,
    crossme_pb.NewGameResponse,
    (request: crossme_pb.NewGameArgs) => {
      return request.serializeBinary();
    },
    crossme_pb.NewGameResponse.deserializeBinary
  );

  newGame(
    request: crossme_pb.NewGameArgs,
    metadata?: grpcWeb.Metadata | null): Promise<crossme_pb.NewGameResponse>;

  newGame(
    request: crossme_pb.NewGameArgs,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: crossme_pb.NewGameResponse) => void): grpcWeb.ClientReadableStream<crossme_pb.NewGameResponse>;

  newGame(
    request: crossme_pb.NewGameArgs,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: crossme_pb.NewGameResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/crossme.CrossMe/NewGame',
        request,
        metadata || {},
        this.methodDescriptorNewGame,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/crossme.CrossMe/NewGame',
    request,
    metadata || {},
    this.methodDescriptorNewGame);
  }

  methodDescriptorGetGameById = new grpcWeb.MethodDescriptor(
    '/crossme.CrossMe/GetGameById',
    grpcWeb.MethodType.UNARY,
    crossme_pb.GetGameByIdArgs,
    crossme_pb.GetGameResponse,
    (request: crossme_pb.GetGameByIdArgs) => {
      return request.serializeBinary();
    },
    crossme_pb.GetGameResponse.deserializeBinary
  );

  getGameById(
    request: crossme_pb.GetGameByIdArgs,
    metadata?: grpcWeb.Metadata | null): Promise<crossme_pb.GetGameResponse>;

  getGameById(
    request: crossme_pb.GetGameByIdArgs,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: crossme_pb.GetGameResponse) => void): grpcWeb.ClientReadableStream<crossme_pb.GetGameResponse>;

  getGameById(
    request: crossme_pb.GetGameByIdArgs,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: crossme_pb.GetGameResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/crossme.CrossMe/GetGameById',
        request,
        metadata || {},
        this.methodDescriptorGetGameById,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/crossme.CrossMe/GetGameById',
    request,
    metadata || {},
    this.methodDescriptorGetGameById);
  }

  methodDescriptorUploadPuzzle = new grpcWeb.MethodDescriptor(
    '/crossme.CrossMe/UploadPuzzle',
    grpcWeb.MethodType.UNARY,
    crossme_pb.UploadPuzzleArgs,
    crossme_pb.UploadPuzzleResponse,
    (request: crossme_pb.UploadPuzzleArgs) => {
      return request.serializeBinary();
    },
    crossme_pb.UploadPuzzleResponse.deserializeBinary
  );

  uploadPuzzle(
    request: crossme_pb.UploadPuzzleArgs,
    metadata?: grpcWeb.Metadata | null): Promise<crossme_pb.UploadPuzzleResponse>;

  uploadPuzzle(
    request: crossme_pb.UploadPuzzleArgs,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: crossme_pb.UploadPuzzleResponse) => void): grpcWeb.ClientReadableStream<crossme_pb.UploadPuzzleResponse>;

  uploadPuzzle(
    request: crossme_pb.UploadPuzzleArgs,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: crossme_pb.UploadPuzzleResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/crossme.CrossMe/UploadPuzzle',
        request,
        metadata || {},
        this.methodDescriptorUploadPuzzle,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/crossme.CrossMe/UploadPuzzle',
    request,
    metadata || {},
    this.methodDescriptorUploadPuzzle);
  }

  methodDescriptorUpdateFill = new grpcWeb.MethodDescriptor(
    '/crossme.CrossMe/UpdateFill',
    grpcWeb.MethodType.UNARY,
    crossme_pb.UpdateFillArgs,
    crossme_pb.UpdateFillResponse,
    (request: crossme_pb.UpdateFillArgs) => {
      return request.serializeBinary();
    },
    crossme_pb.UpdateFillResponse.deserializeBinary
  );

  updateFill(
    request: crossme_pb.UpdateFillArgs,
    metadata?: grpcWeb.Metadata | null): Promise<crossme_pb.UpdateFillResponse>;

  updateFill(
    request: crossme_pb.UpdateFillArgs,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: crossme_pb.UpdateFillResponse) => void): grpcWeb.ClientReadableStream<crossme_pb.UpdateFillResponse>;

  updateFill(
    request: crossme_pb.UpdateFillArgs,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: crossme_pb.UpdateFillResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/crossme.CrossMe/UpdateFill',
        request,
        metadata || {},
        this.methodDescriptorUpdateFill,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/crossme.CrossMe/UpdateFill',
    request,
    metadata || {},
    this.methodDescriptorUpdateFill);
  }

  methodDescriptorSubscribe = new grpcWeb.MethodDescriptor(
    '/crossme.CrossMe/Subscribe',
    grpcWeb.MethodType.SERVER_STREAMING,
    crossme_pb.SubscribeArgs,
    crossme_pb.SubscribeEvent,
    (request: crossme_pb.SubscribeArgs) => {
      return request.serializeBinary();
    },
    crossme_pb.SubscribeEvent.deserializeBinary
  );

  subscribe(
    request: crossme_pb.SubscribeArgs,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<crossme_pb.SubscribeEvent> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/crossme.CrossMe/Subscribe',
      request,
      metadata || {},
      this.methodDescriptorSubscribe);
  }

}

