// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: crossme.proto

package pbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	pb "crossme.app/src/pb"
	errors "errors"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CrossMeName is the fully-qualified name of the CrossMe service.
	CrossMeName = "crossme.CrossMe"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CrossMeGetPuzzleIndexProcedure is the fully-qualified name of the CrossMe's GetPuzzleIndex RPC.
	CrossMeGetPuzzleIndexProcedure = "/crossme.CrossMe/GetPuzzleIndex"
	// CrossMeGetPuzzleByIdProcedure is the fully-qualified name of the CrossMe's GetPuzzleById RPC.
	CrossMeGetPuzzleByIdProcedure = "/crossme.CrossMe/GetPuzzleById"
	// CrossMeNewGameProcedure is the fully-qualified name of the CrossMe's NewGame RPC.
	CrossMeNewGameProcedure = "/crossme.CrossMe/NewGame"
	// CrossMeGetGameByIdProcedure is the fully-qualified name of the CrossMe's GetGameById RPC.
	CrossMeGetGameByIdProcedure = "/crossme.CrossMe/GetGameById"
	// CrossMeUploadPuzzleProcedure is the fully-qualified name of the CrossMe's UploadPuzzle RPC.
	CrossMeUploadPuzzleProcedure = "/crossme.CrossMe/UploadPuzzle"
	// CrossMeUpdateFillProcedure is the fully-qualified name of the CrossMe's UpdateFill RPC.
	CrossMeUpdateFillProcedure = "/crossme.CrossMe/UpdateFill"
	// CrossMeSubscribeProcedure is the fully-qualified name of the CrossMe's Subscribe RPC.
	CrossMeSubscribeProcedure = "/crossme.CrossMe/Subscribe"
	// CrossMeGetSelfProcedure is the fully-qualified name of the CrossMe's GetSelf RPC.
	CrossMeGetSelfProcedure = "/crossme.CrossMe/GetSelf"
	// CrossMeGetMyGamesProcedure is the fully-qualified name of the CrossMe's GetMyGames RPC.
	CrossMeGetMyGamesProcedure = "/crossme.CrossMe/GetMyGames"
	// CrossMeRecordPlaysProcedure is the fully-qualified name of the CrossMe's RecordPlays RPC.
	CrossMeRecordPlaysProcedure = "/crossme.CrossMe/RecordPlays"
)

// CrossMeClient is a client for the crossme.CrossMe service.
type CrossMeClient interface {
	GetPuzzleIndex(context.Context, *connect.Request[pb.GetPuzzleIndexArgs]) (*connect.Response[pb.GetPuzzleIndexResponse], error)
	GetPuzzleById(context.Context, *connect.Request[pb.GetPuzzleByIdArgs]) (*connect.Response[pb.GetPuzzleResponse], error)
	NewGame(context.Context, *connect.Request[pb.NewGameArgs]) (*connect.Response[pb.NewGameResponse], error)
	GetGameById(context.Context, *connect.Request[pb.GetGameByIdArgs]) (*connect.Response[pb.GetGameResponse], error)
	UploadPuzzle(context.Context, *connect.Request[pb.UploadPuzzleArgs]) (*connect.Response[pb.UploadPuzzleResponse], error)
	UpdateFill(context.Context, *connect.Request[pb.UpdateFillArgs]) (*connect.Response[pb.UpdateFillResponse], error)
	Subscribe(context.Context, *connect.Request[pb.SubscribeArgs]) (*connect.ServerStreamForClient[pb.SubscribeEvent], error)
	// Who am I? Resolves the caller's session cookie; the session
	// itself is managed by the HTTP endpoints under /api/auth/.
	GetSelf(context.Context, *connect.Request[pb.GetSelfArgs]) (*connect.Response[pb.GetSelfResponse], error)
	// The games the signed-in caller has played, most recent first.
	// Anonymous callers have no server-side history and get an empty
	// list.
	GetMyGames(context.Context, *connect.Request[pb.GetMyGamesArgs]) (*connect.Response[pb.GetMyGamesResponse], error)
	// Merge a batch of plays into the signed-in caller's history. The
	// client uses this to fold the browser-local "recent games" list —
	// in particular, games played before signing in — into the account.
	// Merging is idempotent: replayed entries only ever widen a game's
	// first/last-played window. A no-op for anonymous callers.
	RecordPlays(context.Context, *connect.Request[pb.RecordPlaysArgs]) (*connect.Response[pb.RecordPlaysResponse], error)
}

// NewCrossMeClient constructs a client for the crossme.CrossMe service. By default, it uses the
// Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCrossMeClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CrossMeClient {
	baseURL = strings.TrimRight(baseURL, "/")
	crossMeMethods := pb.File_crossme_proto.Services().ByName("CrossMe").Methods()
	return &crossMeClient{
		getPuzzleIndex: connect.NewClient[pb.GetPuzzleIndexArgs, pb.GetPuzzleIndexResponse](
			httpClient,
			baseURL+CrossMeGetPuzzleIndexProcedure,
			connect.WithSchema(crossMeMethods.ByName("GetPuzzleIndex")),
			connect.WithClientOptions(opts...),
		),
		getPuzzleById: connect.NewClient[pb.GetPuzzleByIdArgs, pb.GetPuzzleResponse](
			httpClient,
			baseURL+CrossMeGetPuzzleByIdProcedure,
			connect.WithSchema(crossMeMethods.ByName("GetPuzzleById")),
			connect.WithClientOptions(opts...),
		),
		newGame: connect.NewClient[pb.NewGameArgs, pb.NewGameResponse](
			httpClient,
			baseURL+CrossMeNewGameProcedure,
			connect.WithSchema(crossMeMethods.ByName("NewGame")),
			connect.WithClientOptions(opts...),
		),
		getGameById: connect.NewClient[pb.GetGameByIdArgs, pb.GetGameResponse](
			httpClient,
			baseURL+CrossMeGetGameByIdProcedure,
			connect.WithSchema(crossMeMethods.ByName("GetGameById")),
			connect.WithClientOptions(opts...),
		),
		uploadPuzzle: connect.NewClient[pb.UploadPuzzleArgs, pb.UploadPuzzleResponse](
			httpClient,
			baseURL+CrossMeUploadPuzzleProcedure,
			connect.WithSchema(crossMeMethods.ByName("UploadPuzzle")),
			connect.WithClientOptions(opts...),
		),
		updateFill: connect.NewClient[pb.UpdateFillArgs, pb.UpdateFillResponse](
			httpClient,
			baseURL+CrossMeUpdateFillProcedure,
			connect.WithSchema(crossMeMethods.ByName("UpdateFill")),
			connect.WithClientOptions(opts...),
		),
		subscribe: connect.NewClient[pb.SubscribeArgs, pb.SubscribeEvent](
			httpClient,
			baseURL+CrossMeSubscribeProcedure,
			connect.WithSchema(crossMeMethods.ByName("Subscribe")),
			connect.WithClientOptions(opts...),
		),
		getSelf: connect.NewClient[pb.GetSelfArgs, pb.GetSelfResponse](
			httpClient,
			baseURL+CrossMeGetSelfProcedure,
			connect.WithSchema(crossMeMethods.ByName("GetSelf")),
			connect.WithClientOptions(opts...),
		),
		getMyGames: connect.NewClient[pb.GetMyGamesArgs, pb.GetMyGamesResponse](
			httpClient,
			baseURL+CrossMeGetMyGamesProcedure,
			connect.WithSchema(crossMeMethods.ByName("GetMyGames")),
			connect.WithClientOptions(opts...),
		),
		recordPlays: connect.NewClient[pb.RecordPlaysArgs, pb.RecordPlaysResponse](
			httpClient,
			baseURL+CrossMeRecordPlaysProcedure,
			connect.WithSchema(crossMeMethods.ByName("RecordPlays")),
			connect.WithClientOptions(opts...),
		),
	}
}

// crossMeClient implements CrossMeClient.
type crossMeClient struct {
	getPuzzleIndex *connect.Client[pb.GetPuzzleIndexArgs, pb.GetPuzzleIndexResponse]
	getPuzzleById  *connect.Client[pb.GetPuzzleByIdArgs, pb.GetPuzzleResponse]
	newGame        *connect.Client[pb.NewGameArgs, pb.NewGameResponse]
	getGameById    *connect.Client[pb.GetGameByIdArgs, pb.GetGameResponse]
	uploadPuzzle   *connect.Client[pb.UploadPuzzleArgs, pb.UploadPuzzleResponse]
	updateFill     *connect.Client[pb.UpdateFillArgs, pb.UpdateFillResponse]
	subscribe      *connect.Client[pb.SubscribeArgs, pb.SubscribeEvent]
	getSelf        *connect.Client[pb.GetSelfArgs, pb.GetSelfResponse]
	getMyGames     *connect.Client[pb.GetMyGamesArgs, pb.GetMyGamesResponse]
	recordPlays    *connect.Client[pb.RecordPlaysArgs, pb.RecordPlaysResponse]
}

// GetPuzzleIndex calls crossme.CrossMe.GetPuzzleIndex.
func (c *crossMeClient) GetPuzzleIndex(ctx context.Context, req *connect.Request[pb.GetPuzzleIndexArgs]) (*connect.Response[pb.GetPuzzleIndexResponse], error) {
	return c.getPuzzleIndex.CallUnary(ctx, req)
}

// GetPuzzleById calls crossme.CrossMe.GetPuzzleById.
func (c *crossMeClient) GetPuzzleById(ctx context.Context, req *connect.Request[pb.GetPuzzleByIdArgs]) (*connect.Response[pb.GetPuzzleResponse], error) {
	return c.getPuzzleById.CallUnary(ctx, req)
}

// NewGame calls crossme.CrossMe.NewGame.
func (c *crossMeClient) NewGame(ctx context.Context, req *connect.Request[pb.NewGameArgs]) (*connect.Response[pb.NewGameResponse], error) {
	return c.newGame.CallUnary(ctx, req)
}

// GetGameById calls crossme.CrossMe.GetGameById.
func (c *crossMeClient) GetGameById(ctx context.Context, req *connect.Request[pb.GetGameByIdArgs]) (*connect.Response[pb.GetGameResponse], error) {
	return c.getGameById.CallUnary(ctx, req)
}

// UploadPuzzle calls crossme.CrossMe.UploadPuzzle.
func (c *crossMeClient) UploadPuzzle(ctx context.Context, req *connect.Request[pb.UploadPuzzleArgs]) (*connect.Response[pb.UploadPuzzleResponse], error) {
	return c.uploadPuzzle.CallUnary(ctx, req)
}

// UpdateFill calls crossme.CrossMe.UpdateFill.
func (c *crossMeClient) UpdateFill(ctx context.Context, req *connect.Request[pb.UpdateFillArgs]) (*connect.Response[pb.UpdateFillResponse], error) {
	return c.updateFill.CallUnary(ctx, req)
}

// Subscribe calls crossme.CrossMe.Subscribe.
func (c *crossMeClient) Subscribe(ctx context.Context, req *connect.Request[pb.SubscribeArgs]) (*connect.ServerStreamForClient[pb.SubscribeEvent], error) {
	return c.subscribe.CallServerStream(ctx, req)
}

// GetSelf calls crossme.CrossMe.GetSelf.
func (c *crossMeClient) GetSelf(ctx context.Context, req *connect.Request[pb.GetSelfArgs]) (*connect.Response[pb.GetSelfResponse], error) {
	return c.getSelf.CallUnary(ctx, req)
}

// GetMyGames calls crossme.CrossMe.GetMyGames.
func (c *crossMeClient) GetMyGames(ctx context.Context, req *connect.Request[pb.GetMyGamesArgs]) (*connect.Response[pb.GetMyGamesResponse], error) {
	return c.getMyGames.CallUnary(ctx, req)
}

// RecordPlays calls crossme.CrossMe.RecordPlays.
func (c *crossMeClient) RecordPlays(ctx context.Context, req *connect.Request[pb.RecordPlaysArgs]) (*connect.Response[pb.RecordPlaysResponse], error) {
	return c.recordPlays.CallUnary(ctx, req)
}

// CrossMeHandler is an implementation of the crossme.CrossMe service.
type CrossMeHandler interface {
	GetPuzzleIndex(context.Context, *connect.Request[pb.GetPuzzleIndexArgs]) (*connect.Response[pb.GetPuzzleIndexResponse], error)
	GetPuzzleById(context.Context, *connect.Request[pb.GetPuzzleByIdArgs]) (*connect.Response[pb.GetPuzzleResponse], error)
	NewGame(context.Context, *connect.Request[pb.NewGameArgs]) (*connect.Response[pb.NewGameResponse], error)
	GetGameById(context.Context, *connect.Request[pb.GetGameByIdArgs]) (*connect.Response[pb.GetGameResponse], error)
	UploadPuzzle(context.Context, *connect.Request[pb.UploadPuzzleArgs]) (*connect.Response[pb.UploadPuzzleResponse], error)
	UpdateFill(context.Context, *connect.Request[pb.UpdateFillArgs]) (*connect.Response[pb.UpdateFillResponse], error)
	Subscribe(context.Context, *connect.Request[pb.SubscribeArgs], *connect.ServerStream[pb.SubscribeEvent]) error
	// Who am I? Resolves the caller's session cookie; the session
	// itself is managed by the HTTP endpoints under /api/auth/.
	GetSelf(context.Context, *connect.Request[pb.GetSelfArgs]) (*connect.Response[pb.GetSelfResponse], error)
	// The games the signed-in caller has played, most recent first.
	// Anonymous callers have no server-side history and get an empty
	// list.
	GetMyGames(context.Context, *connect.Request[pb.GetMyGamesArgs]) (*connect.Response[pb.GetMyGamesResponse], error)
	// Merge a batch of plays into the signed-in caller's history. The
	// client uses this to fold the browser-local "recent games" list —
	// in particular, games played before signing in — into the account.
	// Merging is idempotent: replayed entries only ever widen a game's
	// first/last-played window. A no-op for anonymous callers.
	RecordPlays(context.Context, *connect.Request[pb.RecordPlaysArgs]) (*connect.Response[pb.RecordPlaysResponse], error)
}

// NewCrossMeHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCrossMeHandler(svc CrossMeHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	crossMeMethods := pb.File_crossme_proto.Services().ByName("CrossMe").Methods()
	crossMeGetPuzzleIndexHandler := connect.NewUnaryHandler(
		CrossMeGetPuzzleIndexProcedure,
		svc.GetPuzzleIndex,
		connect.WithSchema(crossMeMethods.ByName("GetPuzzleIndex")),
		connect.WithHandlerOptions(opts...),
	)
	crossMeGetPuzzleByIdHandler := connect.NewUnaryHandler(
		CrossMeGetPuzzleByIdProcedure,
		svc.GetPuzzleById,
		connect.WithSchema(crossMeMethods.ByName("GetPuzzleById")),
		connect.WithHandlerOptions(opts...),
	)
	crossMeNewGameHandler := connect.NewUnaryHandler(
		CrossMeNewGameProcedure,
		svc.NewGame,
		connect.WithSchema(crossMeMethods.ByName("NewGame")),
		connect.WithHandlerOptions(opts...),
	)
	crossMeGetGameByIdHandler := connect.NewUnaryHandler(
		CrossMeGetGameByIdProcedure,
		svc.GetGameById,
		connect.WithSchema(crossMeMethods.ByName("GetGameById")),
		connect.WithHandlerOptions(opts...),
	)
	crossMeUploadPuzzleHandler := connect.NewUnaryHandler(
		CrossMeUploadPuzzleProcedure,
		svc.UploadPuzzle,
		connect.WithSchema(crossMeMethods.ByName("UploadPuzzle")),
		connect.WithHandlerOptions(opts...),
	)
	crossMeUpdateFillHandler := connect.NewUnaryHandler(
		CrossMeUpdateFillProcedure,
		svc.UpdateFill,
		connect.WithSchema(crossMeMethods.ByName("UpdateFill")),
		connect.WithHandlerOptions(opts...),
	)
	crossMeSubscribeHandler := connect.NewServerStreamHandler(
		CrossMeSubscribeProcedure,
		svc.Subscribe,
		connect.WithSchema(crossMeMethods.ByName("Subscribe")),
		connect.WithHandlerOptions(opts...),
	)
	crossMeGetSelfHandler := connect.NewUnaryHandler(
		CrossMeGetSelfProcedure,
		svc.GetSelf,
		connect.WithSchema(crossMeMethods.ByName("GetSelf")),
		connect.WithHandlerOptions(opts...),
	)
	crossMeGetMyGamesHandler := connect.NewUnaryHandler(
		CrossMeGetMyGamesProcedure,
		svc.GetMyGames,
		connect.WithSchema(crossMeMethods.ByName("GetMyGames")),
		connect.WithHandlerOptions(opts...),
	)
	crossMeRecordPlaysHandler := connect.NewUnaryHandler(
		CrossMeRecordPlaysProcedure,
		svc.RecordPlays,
		connect.WithSchema(crossMeMethods.ByName("RecordPlays")),
		connect.WithHandlerOptions(opts...),
	)
	return "/crossme.CrossMe/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CrossMeGetPuzzleIndexProcedure:
			crossMeGetPuzzleIndexHandler.ServeHTTP(w, r)
		case CrossMeGetPuzzleByIdProcedure:
			crossMeGetPuzzleByIdHandler.ServeHTTP(w, r)
		case CrossMeNewGameProcedure:
			crossMeNewGameHandler.ServeHTTP(w, r)
		case CrossMeGetGameByIdProcedure:
			crossMeGetGameByIdHandler.ServeHTTP(w, r)
		case CrossMeUploadPuzzleProcedure:
			crossMeUploadPuzzleHandler.ServeHTTP(w, r)
		case CrossMeUpdateFillProcedure:
			crossMeUpdateFillHandler.ServeHTTP(w, r)
		case CrossMeSubscribeProcedure:
			crossMeSubscribeHandler.ServeHTTP(w, r)
		case CrossMeGetSelfProcedure:
			crossMeGetSelfHandler.ServeHTTP(w, r)
		case CrossMeGetMyGamesProcedure:
			crossMeGetMyGamesHandler.ServeHTTP(w, r)
		case CrossMeRecordPlaysProcedure:
			crossMeRecordPlaysHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCrossMeHandler returns CodeUnimplemented from all methods.
type UnimplementedCrossMeHandler struct{}

func (UnimplementedCrossMeHandler) GetPuzzleIndex(context.Context, *connect.Request[pb.GetPuzzleIndexArgs]) (*connect.Response[pb.GetPuzzleIndexResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("crossme.CrossMe.GetPuzzleIndex is not implemented"))
}

func (UnimplementedCrossMeHandler) GetPuzzleById(context.Context, *connect.Request[pb.GetPuzzleByIdArgs]) (*connect.Response[pb.GetPuzzleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("crossme.CrossMe.GetPuzzleById is not implemented"))
}

func (UnimplementedCrossMeHandler) NewGame(context.Context, *connect.Request[pb.NewGameArgs]) (*connect.Response[pb.NewGameResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("crossme.CrossMe.NewGame is not implemented"))
}

func (UnimplementedCrossMeHandler) GetGameById(context.Context, *connect.Request[pb.GetGameByIdArgs]) (*connect.Response[pb.GetGameResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("crossme.CrossMe.GetGameById is not implemented"))
}

func (UnimplementedCrossMeHandler) UploadPuzzle(context.Context, *connect.Request[pb.UploadPuzzleArgs]) (*connect.Response[pb.UploadPuzzleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("crossme.CrossMe.UploadPuzzle is not implemented"))
}

func (UnimplementedCrossMeHandler) UpdateFill(context.Context, *connect.Request[pb.UpdateFillArgs]) (*connect.Response[pb.UpdateFillResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("crossme.CrossMe.UpdateFill is not implemented"))
}

func (UnimplementedCrossMeHandler) Subscribe(context.Context, *connect.Request[pb.SubscribeArgs], *connect.ServerStream[pb.SubscribeEvent]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("crossme.CrossMe.Subscribe is not implemented"))
}

func (UnimplementedCrossMeHandler) GetSelf(context.Context, *connect.Request[pb.GetSelfArgs]) (*connect.Response[pb.GetSelfResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("crossme.CrossMe.GetSelf is not implemented"))
}

func (UnimplementedCrossMeHandler) GetMyGames(context.Context, *connect.Request[pb.GetMyGamesArgs]) (*connect.Response[pb.GetMyGamesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("crossme.CrossMe.GetMyGames is not implemented"))
}

func (UnimplementedCrossMeHandler) RecordPlays(context.Context, *connect.Request[pb.RecordPlaysArgs]) (*connect.Response[pb.RecordPlaysResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("crossme.CrossMe.RecordPlays is not implemented"))
}
