#!/bin/bash
set -eu
cd "$(dirname "$0")/.."
protoc -Ipb \
       --go_out=paths=source_relative,plugins=grpc:pb \
       --js_out=import_style=commonjs:client/src/pb/ \
       --grpc-web_out=import_style=typescript,mode=grpcwebtext:client/src/pb/ \
       pb/*.proto
