// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: crossme.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetPuzzleIndexArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPuzzleIndexArgs) Reset() {
	*x = GetPuzzleIndexArgs{}
	mi := &file_crossme_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPuzzleIndexArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPuzzleIndexArgs) ProtoMessage() {}

func (x *GetPuzzleIndexArgs) ProtoReflect() protoreflect.Message {
	mi := &file_crossme_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPuzzleIndexArgs.ProtoReflect.Descriptor instead.
func (*GetPuzzleIndexArgs) Descriptor() ([]byte, []int) {
	return file_crossme_proto_rawDescGZIP(), []int{0}
}

type GetPuzzleIndexResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Puzzles       []*PuzzleIndex         `protobuf:"bytes,1,rep,name=puzzles,proto3" json:"puzzles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPuzzleIndexResponse) Reset() {
	*x = GetPuzzleIndexResponse{}
	mi := &file_crossme_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPuzzleIndexResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPuzzleIndexResponse) ProtoMessage() {}

func (x *GetPuzzleIndexResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crossme_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPuzzleIndexResponse.ProtoReflect.Descriptor instead.
func (*GetPuzzleIndexResponse) Descriptor() ([]byte, []int) {
	return file_crossme_proto_rawDescGZIP(), []int{1}
}

func (x *GetPuzzleIndexResponse) GetPuzzles() []*PuzzleIndex {
	if x != nil {
		return x.Puzzles
	}
	return nil
}

type GetPuzzleByIdArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPuzzleByIdArgs) Reset() {
	*x = GetPuzzleByIdArgs{}
	mi := &file_crossme_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPuzzleByIdArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPuzzleByIdArgs) ProtoMessage() {}

func (x *GetPuzzleByIdArgs) ProtoReflect() protoreflect.Message {
	mi := &file_crossme_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPuzzleByIdArgs.ProtoReflect.Descriptor instead.
func (*GetPuzzleByIdArgs) Descriptor() ([]byte, []int) {
	return file_crossme_proto_rawDescGZIP(), []int{2}
}

func (x *GetPuzzleByIdArgs) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPuzzleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Puzzle        *Puzzle                `protobuf:"bytes,1,opt,name=puzzle,proto3" json:"puzzle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPuzzleResponse) Reset() {
	*x = GetPuzzleResponse{}
	mi := &file_crossme_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPuzzleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPuzzleResponse) ProtoMessage() {}

func (x *GetPuzzleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crossme_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPuzzleResponse.ProtoReflect.Descriptor instead.
func (*GetPuzzleResponse) Descriptor() ([]byte, []int) {
	return file_crossme_proto_rawDescGZIP(), []int{3}
}

func (x *GetPuzzleResponse) GetPuzzle() *Puzzle {
	if x != nil {
		return x.Puzzle
	}
	return nil
}

type NewGameArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PuzzleId      string                 `protobuf:"bytes,1,opt,name=puzzle_id,json=puzzleId,proto3" json:"puzzle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewGameArgs) Reset() {
	*x = NewGameArgs{}
	mi := &file_crossme_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewGameArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewGameArgs) ProtoMessage() {}

func (x *NewGameArgs) ProtoReflect() protoreflect.Message {
	mi := &file_crossme_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewGameArgs.ProtoReflect.Descriptor instead.
func (*NewGameArgs) Descriptor() ([]byte, []int) {
	return file_crossme_proto_rawDescGZIP(), []int{4}
}

func (x *NewGameArgs) GetPuzzleId() string {
	if x != nil {
		return x.PuzzleId
	}
	return ""
}

type NewGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *Game                  `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewGameResponse) Reset() {
	*x = NewGameResponse{}
	mi := &file_crossme_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewGameResponse) ProtoMessage() {}

func (x *NewGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crossme_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewGameResponse.ProtoReflect.Descriptor instead.
func (*NewGameResponse) Descriptor() ([]byte, []int) {
	return file_crossme_proto_rawDescGZIP(), []int{5}
}

func (x *NewGameResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

type GetGameByIdArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameByIdArgs) Reset() {
	*x = GetGameByIdArgs{}
	mi := &file_crossme_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameByIdArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameByIdArgs) ProtoMessage() {}

func (x *GetGameByIdArgs) ProtoReflect() protoreflect.Message {
	mi := &file_crossme_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameByIdArgs.ProtoReflect.Descriptor instead.
func (*GetGameByIdArgs) Descriptor() ([]byte, []int) {
	return file_crossme_proto_rawDescGZIP(), []int{6}
}

func (x *GetGameByIdArgs) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetGameResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *Game                  `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	Puzzle        *Puzzle                `protobuf:"bytes,2,opt,name=puzzle,proto3" json:"puzzle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameResponse) Reset() {
	*x = GetGameResponse{}
	mi := &file_crossme_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameResponse) ProtoMessage() {}

func (x *GetGameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crossme_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameResponse.ProtoReflect.Descriptor instead.
func (*GetGameResponse) Descriptor() ([]byte, []int) {
	return file_crossme_proto_rawDescGZIP(), []int{7}
}

func (x *GetGameResponse) GetGame() *Game {
	if x != nil {
		return x.Game
	}
	return nil
}

func (x *GetGameResponse) GetPuzzle() *Puzzle {
	if x != nil {
		return x.Puzzle
	}
	return nil
}

type UploadPuzzleArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPuzzleArgs) Reset() {
	*x = UploadPuzzleArgs{}
	mi := &file_crossme_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPuzzleArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPuzzleArgs) ProtoMessage() {}

func (x *UploadPuzzleArgs) ProtoReflect() protoreflect.Message {
	mi := &file_crossme_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPuzzleArgs.ProtoReflect.Descriptor instead.
func (*UploadPuzzleArgs) Descriptor() ([]byte, []int) {
	return file_crossme_proto_rawDescGZIP(), []int{8}
}

func (x *UploadPuzzleArgs) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadPuzzleArgs) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadPuzzleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Puzzle        *Puzzle                `protobuf:"bytes,1,opt,name=puzzle,proto3" json:"puzzle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadPuzzleResponse) Reset() {
	*x = UploadPuzzleResponse{}
	mi := &file_crossme_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadPuzzleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadPuzzleResponse) ProtoMessage() {}

func (x *UploadPuzzleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crossme_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadPuzzleResponse.ProtoReflect.Descriptor instead.
func (*UploadPuzzleResponse) Descriptor() ([]byte, []int) {
	return file_crossme_proto_rawDescGZIP(), []int{9}
}

func (x *UploadPuzzleResponse) GetPuzzle() *Puzzle {
	if x != nil {
		return x.Puzzle
	}
	return nil
}

type SubscribeArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeArgs) Reset() {
	*x = SubscribeArgs{}
	mi := &file_crossme_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeArgs) ProtoMessage() {}

func (x *SubscribeArgs) ProtoReflect() protoreflect.Message {
	mi := &file_crossme_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeArgs.ProtoReflect.Descriptor instead.
func (*SubscribeArgs) Descriptor() ([]byte, []int) {
	return file_crossme_proto_rawDescGZIP(), []int{10}
}

func (x *SubscribeArgs) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *SubscribeArgs) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type SubscribeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fill          *Fill                  `protobuf:"bytes,1,opt,name=fill,proto3" json:"fill,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeEvent) Reset() {
	*x = SubscribeEvent{}
	mi := &file_crossme_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeEvent) ProtoMessage() {}

func (x *SubscribeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_crossme_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeEvent.ProtoReflect.Descriptor instead.
func (*SubscribeEvent) Descriptor() ([]byte, []int) {
	return file_crossme_proto_rawDescGZIP(), []int{11}
}

func (x *SubscribeEvent) GetFill() *Fill {
	if x != nil {
		return x.Fill
	}
	return nil
}

type UpdateFillArgs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameId        string                 `protobuf:"bytes,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Fill          *Fill                  `protobuf:"bytes,3,opt,name=fill,proto3" json:"fill,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFillArgs) Reset() {
	*x = UpdateFillArgs{}
	mi := &file_crossme_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFillArgs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFillArgs) ProtoMessage() {}

func (x *UpdateFillArgs) ProtoReflect() protoreflect.Message {
	mi := &file_crossme_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFillArgs.ProtoReflect.Descriptor instead.
func (*UpdateFillArgs) Descriptor() ([]byte, []int) {
	return file_crossme_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateFillArgs) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *UpdateFillArgs) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *UpdateFillArgs) GetFill() *Fill {
	if x != nil {
		return x.Fill
	}
	return nil
}

type UpdateFillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFillResponse) Reset() {
	*x = UpdateFillResponse{}
	mi := &file_crossme_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFillResponse) ProtoMessage() {}

func (x *UpdateFillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crossme_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFillResponse.ProtoReflect.Descriptor instead.
func (*UpdateFillResponse) Descriptor() ([]byte, []int) {
	return file_crossme_proto_rawDescGZIP(), []int{13}
}

var File_crossme_proto protoreflect.FileDescriptor

const file_crossme_proto_rawDesc = "" +
	"\n" +
	"\rcrossme.proto\x12\acrossme\x1a\fpuzzle.proto\x1a\n" +
	"fill.proto\x1a\n" +
	"game.proto\"\x14\n" +
	"\x12GetPuzzleIndexArgs\"H\n" +
	"\x16GetPuzzleIndexResponse\x12.\n" +
	"\apuzzles\x18\x01 \x03(\v2\x14.crossme.PuzzleIndexR\apuzzles\"#\n" +
	"\x11GetPuzzleByIdArgs\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"<\n" +
	"\x11GetPuzzleResponse\x12'\n" +
	"\x06puzzle\x18\x01 \x01(\v2\x0f.crossme.PuzzleR\x06puzzle\"*\n" +
	"\vNewGameArgs\x12\x1b\n" +
	"\tpuzzle_id\x18\x01 \x01(\tR\bpuzzleId\"4\n" +
	"\x0fNewGameResponse\x12!\n" +
	"\x04game\x18\x01 \x01(\v2\r.crossme.GameR\x04game\"!\n" +
	"\x0fGetGameByIdArgs\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"]\n" +
	"\x0fGetGameResponse\x12!\n" +
	"\x04game\x18\x01 \x01(\v2\r.crossme.GameR\x04game\x12'\n" +
	"\x06puzzle\x18\x02 \x01(\v2\x0f.crossme.PuzzleR\x06puzzle\"B\n" +
	"\x10UploadPuzzleArgs\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\"?\n" +
	"\x14UploadPuzzleResponse\x12'\n" +
	"\x06puzzle\x18\x01 \x01(\v2\x0f.crossme.PuzzleR\x06puzzle\"A\n" +
	"\rSubscribeArgs\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\"3\n" +
	"\x0eSubscribeEvent\x12!\n" +
	"\x04fill\x18\x01 \x01(\v2\r.crossme.FillR\x04fill\"e\n" +
	"\x0eUpdateFillArgs\x12\x17\n" +
	"\agame_id\x18\x01 \x01(\tR\x06gameId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12!\n" +
	"\x04fill\x18\x03 \x01(\v2\r.crossme.FillR\x04fill\"\x14\n" +
	"\x12UpdateFillResponse2\xee\x03\n" +
	"\aCrossMe\x12N\n" +
	"\x0eGetPuzzleIndex\x12\x1b.crossme.GetPuzzleIndexArgs\x1a\x1f.crossme.GetPuzzleIndexResponse\x12G\n" +
	"\rGetPuzzleById\x12\x1a.crossme.GetPuzzleByIdArgs\x1a\x1a.crossme.GetPuzzleResponse\x129\n" +
	"\aNewGame\x12\x14.crossme.NewGameArgs\x1a\x18.crossme.NewGameResponse\x12A\n" +
	"\vGetGameById\x12\x18.crossme.GetGameByIdArgs\x1a\x18.crossme.GetGameResponse\x12H\n" +
	"\fUploadPuzzle\x12\x19.crossme.UploadPuzzleArgs\x1a\x1d.crossme.UploadPuzzleResponse\x12B\n" +
	"\n" +
	"UpdateFill\x12\x17.crossme.UpdateFillArgs\x1a\x1b.crossme.UpdateFillResponse\x12>\n" +
	"\tSubscribe\x12\x16.crossme.SubscribeArgs\x1a\x17.crossme.SubscribeEvent0\x01B\x14Z\x12crossme.app/src/pbb\x06proto3"

var (
	file_crossme_proto_rawDescOnce sync.Once
	file_crossme_proto_rawDescData []byte
)

func file_crossme_proto_rawDescGZIP() []byte {
	file_crossme_proto_rawDescOnce.Do(func() {
		file_crossme_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crossme_proto_rawDesc), len(file_crossme_proto_rawDesc)))
	})
	return file_crossme_proto_rawDescData
}

var file_crossme_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_crossme_proto_goTypes = []any{
	(*GetPuzzleIndexArgs)(nil),     // 0: crossme.GetPuzzleIndexArgs
	(*GetPuzzleIndexResponse)(nil), // 1: crossme.GetPuzzleIndexResponse
	(*GetPuzzleByIdArgs)(nil),      // 2: crossme.GetPuzzleByIdArgs
	(*GetPuzzleResponse)(nil),      // 3: crossme.GetPuzzleResponse
	(*NewGameArgs)(nil),            // 4: crossme.NewGameArgs
	(*NewGameResponse)(nil),        // 5: crossme.NewGameResponse
	(*GetGameByIdArgs)(nil),        // 6: crossme.GetGameByIdArgs
	(*GetGameResponse)(nil),        // 7: crossme.GetGameResponse
	(*UploadPuzzleArgs)(nil),       // 8: crossme.UploadPuzzleArgs
	(*UploadPuzzleResponse)(nil),   // 9: crossme.UploadPuzzleResponse
	(*SubscribeArgs)(nil),          // 10: crossme.SubscribeArgs
	(*SubscribeEvent)(nil),         // 11: crossme.SubscribeEvent
	(*UpdateFillArgs)(nil),         // 12: crossme.UpdateFillArgs
	(*UpdateFillResponse)(nil),     // 13: crossme.UpdateFillResponse
	(*PuzzleIndex)(nil),            // 14: crossme.PuzzleIndex
	(*Puzzle)(nil),                 // 15: crossme.Puzzle
	(*Game)(nil),                   // 16: crossme.Game
	(*Fill)(nil),                   // 17: crossme.Fill
}
var file_crossme_proto_depIdxs = []int32{
	14, // 0: crossme.GetPuzzleIndexResponse.puzzles:type_name -> crossme.PuzzleIndex
	15, // 1: crossme.GetPuzzleResponse.puzzle:type_name -> crossme.Puzzle
	16, // 2: crossme.NewGameResponse.game:type_name -> crossme.Game
	16, // 3: crossme.GetGameResponse.game:type_name -> crossme.Game
	15, // 4: crossme.GetGameResponse.puzzle:type_name -> crossme.Puzzle
	15, // 5: crossme.UploadPuzzleResponse.puzzle:type_name -> crossme.Puzzle
	17, // 6: crossme.SubscribeEvent.fill:type_name -> crossme.Fill
	17, // 7: crossme.UpdateFillArgs.fill:type_name -> crossme.Fill
	0,  // 8: crossme.CrossMe.GetPuzzleIndex:input_type -> crossme.GetPuzzleIndexArgs
	2,  // 9: crossme.CrossMe.GetPuzzleById:input_type -> crossme.GetPuzzleByIdArgs
	4,  // 10: crossme.CrossMe.NewGame:input_type -> crossme.NewGameArgs
	6,  // 11: crossme.CrossMe.GetGameById:input_type -> crossme.GetGameByIdArgs
	8,  // 12: crossme.CrossMe.UploadPuzzle:input_type -> crossme.UploadPuzzleArgs
	12, // 13: crossme.CrossMe.UpdateFill:input_type -> crossme.UpdateFillArgs
	10, // 14: crossme.CrossMe.Subscribe:input_type -> crossme.SubscribeArgs
	1,  // 15: crossme.CrossMe.GetPuzzleIndex:output_type -> crossme.GetPuzzleIndexResponse
	3,  // 16: crossme.CrossMe.GetPuzzleById:output_type -> crossme.GetPuzzleResponse
	5,  // 17: crossme.CrossMe.NewGame:output_type -> crossme.NewGameResponse
	7,  // 18: crossme.CrossMe.GetGameById:output_type -> crossme.GetGameResponse
	9,  // 19: crossme.CrossMe.UploadPuzzle:output_type -> crossme.UploadPuzzleResponse
	13, // 20: crossme.CrossMe.UpdateFill:output_type -> crossme.UpdateFillResponse
	11, // 21: crossme.CrossMe.Subscribe:output_type -> crossme.SubscribeEvent
	15, // [15:22] is the sub-list for method output_type
	8,  // [8:15] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_crossme_proto_init() }
func file_crossme_proto_init() {
	if File_crossme_proto != nil {
		return
	}
	file_puzzle_proto_init()
	file_fill_proto_init()
	file_game_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crossme_proto_rawDesc), len(file_crossme_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_crossme_proto_goTypes,
		DependencyIndexes: file_crossme_proto_depIdxs,
		MessageInfos:      file_crossme_proto_msgTypes,
	}.Build()
	File_crossme_proto = out.File
	file_crossme_proto_goTypes = nil
	file_crossme_proto_depIdxs = nil
}
