// Code generated by protoc-gen-go. DO NOT EDIT.
// source: puzzle.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Puzzle struct {
	Title                string         `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author               string         `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Copyright            string         `protobuf:"bytes,3,opt,name=copyright,proto3" json:"copyright,omitempty"`
	Note                 string         `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	Width                int32          `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height               int32          `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	Squares              []*Puzzle_Cell `protobuf:"bytes,8,rep,name=squares,proto3" json:"squares,omitempty"`
	AcrossClues          []*Puzzle_Clue `protobuf:"bytes,9,rep,name=across_clues,json=acrossClues,proto3" json:"across_clues,omitempty"`
	DownClues            []*Puzzle_Clue `protobuf:"bytes,10,rep,name=down_clues,json=downClues,proto3" json:"down_clues,omitempty"`
	Metadata             *Puzzle_Meta   `protobuf:"bytes,11,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Puzzle) Reset()         { *m = Puzzle{} }
func (m *Puzzle) String() string { return proto.CompactTextString(m) }
func (*Puzzle) ProtoMessage()    {}
func (*Puzzle) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3faac3a9309578f, []int{0}
}

func (m *Puzzle) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Puzzle.Unmarshal(m, b)
}
func (m *Puzzle) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Puzzle.Marshal(b, m, deterministic)
}
func (m *Puzzle) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Puzzle.Merge(m, src)
}
func (m *Puzzle) XXX_Size() int {
	return xxx_messageInfo_Puzzle.Size(m)
}
func (m *Puzzle) XXX_DiscardUnknown() {
	xxx_messageInfo_Puzzle.DiscardUnknown(m)
}

var xxx_messageInfo_Puzzle proto.InternalMessageInfo

func (m *Puzzle) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Puzzle) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Puzzle) GetCopyright() string {
	if m != nil {
		return m.Copyright
	}
	return ""
}

func (m *Puzzle) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *Puzzle) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Puzzle) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Puzzle) GetSquares() []*Puzzle_Cell {
	if m != nil {
		return m.Squares
	}
	return nil
}

func (m *Puzzle) GetAcrossClues() []*Puzzle_Clue {
	if m != nil {
		return m.AcrossClues
	}
	return nil
}

func (m *Puzzle) GetDownClues() []*Puzzle_Clue {
	if m != nil {
		return m.DownClues
	}
	return nil
}

func (m *Puzzle) GetMetadata() *Puzzle_Meta {
	if m != nil {
		return m.Metadata
	}
	return nil
}

type Puzzle_Cell struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Black                bool     `protobuf:"varint,2,opt,name=black,proto3" json:"black,omitempty"`
	Circled              bool     `protobuf:"varint,3,opt,name=circled,proto3" json:"circled,omitempty"`
	Fill                 string   `protobuf:"bytes,4,opt,name=fill,proto3" json:"fill,omitempty"`
	ClueAcross           int32    `protobuf:"varint,5,opt,name=clue_across,json=clueAcross,proto3" json:"clue_across,omitempty"`
	ClueDown             int32    `protobuf:"varint,6,opt,name=clue_down,json=clueDown,proto3" json:"clue_down,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Puzzle_Cell) Reset()         { *m = Puzzle_Cell{} }
func (m *Puzzle_Cell) String() string { return proto.CompactTextString(m) }
func (*Puzzle_Cell) ProtoMessage()    {}
func (*Puzzle_Cell) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3faac3a9309578f, []int{0, 0}
}

func (m *Puzzle_Cell) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Puzzle_Cell.Unmarshal(m, b)
}
func (m *Puzzle_Cell) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Puzzle_Cell.Marshal(b, m, deterministic)
}
func (m *Puzzle_Cell) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Puzzle_Cell.Merge(m, src)
}
func (m *Puzzle_Cell) XXX_Size() int {
	return xxx_messageInfo_Puzzle_Cell.Size(m)
}
func (m *Puzzle_Cell) XXX_DiscardUnknown() {
	xxx_messageInfo_Puzzle_Cell.DiscardUnknown(m)
}

var xxx_messageInfo_Puzzle_Cell proto.InternalMessageInfo

func (m *Puzzle_Cell) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Puzzle_Cell) GetBlack() bool {
	if m != nil {
		return m.Black
	}
	return false
}

func (m *Puzzle_Cell) GetCircled() bool {
	if m != nil {
		return m.Circled
	}
	return false
}

func (m *Puzzle_Cell) GetFill() string {
	if m != nil {
		return m.Fill
	}
	return ""
}

func (m *Puzzle_Cell) GetClueAcross() int32 {
	if m != nil {
		return m.ClueAcross
	}
	return 0
}

func (m *Puzzle_Cell) GetClueDown() int32 {
	if m != nil {
		return m.ClueDown
	}
	return 0
}

type Puzzle_Clue struct {
	Number               int32    `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Puzzle_Clue) Reset()         { *m = Puzzle_Clue{} }
func (m *Puzzle_Clue) String() string { return proto.CompactTextString(m) }
func (*Puzzle_Clue) ProtoMessage()    {}
func (*Puzzle_Clue) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3faac3a9309578f, []int{0, 1}
}

func (m *Puzzle_Clue) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Puzzle_Clue.Unmarshal(m, b)
}
func (m *Puzzle_Clue) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Puzzle_Clue.Marshal(b, m, deterministic)
}
func (m *Puzzle_Clue) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Puzzle_Clue.Merge(m, src)
}
func (m *Puzzle_Clue) XXX_Size() int {
	return xxx_messageInfo_Puzzle_Clue.Size(m)
}
func (m *Puzzle_Clue) XXX_DiscardUnknown() {
	xxx_messageInfo_Puzzle_Clue.DiscardUnknown(m)
}

var xxx_messageInfo_Puzzle_Clue proto.InternalMessageInfo

func (m *Puzzle_Clue) GetNumber() int32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *Puzzle_Clue) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

type Puzzle_Meta struct {
	Created *timestamp.Timestamp `protobuf:"bytes,1,opt,name=created,proto3" json:"created,omitempty"`
	// sha256 of the .puz file that imported to this puzzle, in
	// hex
	Sha256 string `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// Unique ID used to refer to this puzzle
	Id string `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	// YYYY-MM-DD parsed date that the puzzle was published, or ""
	Date                 string   `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Puzzle_Meta) Reset()         { *m = Puzzle_Meta{} }
func (m *Puzzle_Meta) String() string { return proto.CompactTextString(m) }
func (*Puzzle_Meta) ProtoMessage()    {}
func (*Puzzle_Meta) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3faac3a9309578f, []int{0, 2}
}

func (m *Puzzle_Meta) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Puzzle_Meta.Unmarshal(m, b)
}
func (m *Puzzle_Meta) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Puzzle_Meta.Marshal(b, m, deterministic)
}
func (m *Puzzle_Meta) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Puzzle_Meta.Merge(m, src)
}
func (m *Puzzle_Meta) XXX_Size() int {
	return xxx_messageInfo_Puzzle_Meta.Size(m)
}
func (m *Puzzle_Meta) XXX_DiscardUnknown() {
	xxx_messageInfo_Puzzle_Meta.DiscardUnknown(m)
}

var xxx_messageInfo_Puzzle_Meta proto.InternalMessageInfo

func (m *Puzzle_Meta) GetCreated() *timestamp.Timestamp {
	if m != nil {
		return m.Created
	}
	return nil
}

func (m *Puzzle_Meta) GetSha256() string {
	if m != nil {
		return m.Sha256
	}
	return ""
}

func (m *Puzzle_Meta) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Puzzle_Meta) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

type PuzzleIndex struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Date                 string   `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PuzzleIndex) Reset()         { *m = PuzzleIndex{} }
func (m *PuzzleIndex) String() string { return proto.CompactTextString(m) }
func (*PuzzleIndex) ProtoMessage()    {}
func (*PuzzleIndex) Descriptor() ([]byte, []int) {
	return fileDescriptor_e3faac3a9309578f, []int{1}
}

func (m *PuzzleIndex) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PuzzleIndex.Unmarshal(m, b)
}
func (m *PuzzleIndex) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PuzzleIndex.Marshal(b, m, deterministic)
}
func (m *PuzzleIndex) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PuzzleIndex.Merge(m, src)
}
func (m *PuzzleIndex) XXX_Size() int {
	return xxx_messageInfo_PuzzleIndex.Size(m)
}
func (m *PuzzleIndex) XXX_DiscardUnknown() {
	xxx_messageInfo_PuzzleIndex.DiscardUnknown(m)
}

var xxx_messageInfo_PuzzleIndex proto.InternalMessageInfo

func (m *PuzzleIndex) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PuzzleIndex) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *PuzzleIndex) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func init() {
	proto.RegisterType((*Puzzle)(nil), "crossme.Puzzle")
	proto.RegisterType((*Puzzle_Cell)(nil), "crossme.Puzzle.Cell")
	proto.RegisterType((*Puzzle_Clue)(nil), "crossme.Puzzle.Clue")
	proto.RegisterType((*Puzzle_Meta)(nil), "crossme.Puzzle.Meta")
	proto.RegisterType((*PuzzleIndex)(nil), "crossme.PuzzleIndex")
}

func init() { proto.RegisterFile("puzzle.proto", fileDescriptor_e3faac3a9309578f) }

var fileDescriptor_e3faac3a9309578f = []byte{
	// 460 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0x55, 0xba, 0x49, 0x9b, 0x4c, 0x56, 0x1c, 0xac, 0x0a, 0x45, 0x01, 0x69, 0xab, 0x3d, 0xf5,
	0x94, 0xa2, 0x2e, 0x1f, 0x67, 0x3e, 0x24, 0xc4, 0x01, 0x09, 0x59, 0x9c, 0xb8, 0xac, 0x9c, 0x64,
	0xb6, 0x89, 0x70, 0xe2, 0x10, 0x3b, 0x6a, 0xd9, 0x5f, 0xc3, 0xbf, 0xe0, 0xef, 0x21, 0x8f, 0xe3,
	0xc2, 0x61, 0x97, 0xdb, 0xbc, 0xc9, 0x7b, 0x93, 0x79, 0xcf, 0x03, 0x97, 0xc3, 0x74, 0x7f, 0x2f,
	0xb1, 0x18, 0x46, 0x65, 0x14, 0x5b, 0x55, 0xa3, 0xd2, 0xba, 0xc3, 0xfc, 0xea, 0xa0, 0xd4, 0x41,
	0xe2, 0x8e, 0xda, 0xe5, 0x74, 0xb7, 0x33, 0x6d, 0x87, 0xda, 0x88, 0x6e, 0x70, 0xcc, 0xeb, 0xdf,
	0x11, 0x2c, 0xbf, 0x90, 0x94, 0xad, 0x21, 0x32, 0xad, 0x91, 0x98, 0x05, 0x9b, 0x60, 0x9b, 0x70,
	0x07, 0xd8, 0x53, 0x58, 0x8a, 0xc9, 0x34, 0x6a, 0xcc, 0x16, 0xd4, 0x9e, 0x11, 0x7b, 0x0e, 0x49,
	0xa5, 0x86, 0x9f, 0x63, 0x7b, 0x68, 0x4c, 0x76, 0x41, 0x9f, 0xfe, 0x36, 0x18, 0x83, 0xb0, 0x57,
	0x06, 0xb3, 0x90, 0x3e, 0x50, 0x6d, 0xe7, 0x1f, 0xdb, 0xda, 0x34, 0x59, 0xb4, 0x09, 0xb6, 0x11,
	0x77, 0xc0, 0xce, 0x6f, 0x90, 0x86, 0x2c, 0xa9, 0x3d, 0x23, 0x56, 0xc0, 0x4a, 0xff, 0x98, 0xc4,
	0x88, 0x3a, 0x8b, 0x37, 0x17, 0xdb, 0x74, 0xbf, 0x2e, 0x66, 0x53, 0x85, 0xdb, 0xb7, 0x78, 0x8f,
	0x52, 0x72, 0x4f, 0x62, 0x6f, 0xe0, 0x52, 0x10, 0xe1, 0xb6, 0x92, 0x13, 0xea, 0x2c, 0x79, 0x44,
	0x24, 0x27, 0xe4, 0xa9, 0x63, 0xda, 0x5a, 0xb3, 0x1b, 0x80, 0x5a, 0x1d, 0xfb, 0x59, 0x06, 0xff,
	0x91, 0x25, 0x96, 0xe7, 0x44, 0x2f, 0x20, 0xee, 0xd0, 0x88, 0x5a, 0x18, 0x91, 0xa5, 0x9b, 0xe0,
	0x21, 0xc9, 0x67, 0x34, 0x82, 0x9f, 0x59, 0xf9, 0xaf, 0x00, 0x42, 0xbb, 0xb1, 0x35, 0xdc, 0x4f,
	0x5d, 0x89, 0x23, 0xe5, 0x1c, 0xf1, 0x19, 0xd9, 0x78, 0x4a, 0x29, 0xaa, 0xef, 0x94, 0x73, 0xcc,
	0x1d, 0x60, 0x19, 0xac, 0xaa, 0x76, 0xac, 0x24, 0xd6, 0x14, 0x72, 0xcc, 0x3d, 0xb4, 0x11, 0xdf,
	0xb5, 0x52, 0xfa, 0x88, 0x6d, 0xcd, 0xae, 0x20, 0xb5, 0x36, 0x6e, 0x9d, 0xbf, 0x39, 0x68, 0xb0,
	0xad, 0xb7, 0xd4, 0x61, 0xcf, 0x20, 0x21, 0x82, 0x75, 0x32, 0x07, 0x1e, 0xdb, 0xc6, 0x07, 0x75,
	0xec, 0xf3, 0x3d, 0x84, 0xd6, 0xdd, 0xa3, 0x1b, 0x32, 0x08, 0x0d, 0x9e, 0xfc, 0x6b, 0x53, 0x9d,
	0x9f, 0x20, 0xb4, 0x46, 0xd9, 0x4b, 0x58, 0x55, 0x23, 0x0a, 0x83, 0x35, 0x89, 0xd2, 0x7d, 0x5e,
	0xb8, 0xd3, 0x2b, 0xfc, 0xe9, 0x15, 0x5f, 0xfd, 0xe9, 0x71, 0x4f, 0xb5, 0x7f, 0xd2, 0x8d, 0xd8,
	0xbf, 0x7a, 0xed, 0x8f, 0xcb, 0x21, 0xf6, 0x04, 0x16, 0x6d, 0x4d, 0xeb, 0x27, 0x7c, 0xd1, 0x92,
	0xd7, 0x5a, 0x18, 0xf4, 0x7f, 0xb6, 0xf5, 0xf5, 0x47, 0x48, 0x5d, 0xd2, 0x9f, 0xfa, 0x1a, 0x4f,
	0xb3, 0x24, 0x38, 0x4b, 0xce, 0xd7, 0xbc, 0xf8, 0xf7, 0x9a, 0x1f, 0x18, 0xf4, 0x6e, 0xfd, 0x8d,
	0xf9, 0xa7, 0x13, 0xc3, 0xb0, 0xd3, 0x63, 0xb5, 0x1b, 0xca, 0x72, 0x49, 0x7b, 0xdf, 0xfc, 0x09,
	0x00, 0x00, 0xff, 0xff, 0x38, 0xb0, 0xf3, 0xb6, 0x59, 0x03, 0x00, 0x00,
}
