// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: puzzle.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Puzzle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Author        string                 `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	Copyright     string                 `protobuf:"bytes,3,opt,name=copyright,proto3" json:"copyright,omitempty"`
	Note          string                 `protobuf:"bytes,4,opt,name=note,proto3" json:"note,omitempty"`
	Width         int32                  `protobuf:"varint,5,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,6,opt,name=height,proto3" json:"height,omitempty"`
	Squares       []*Puzzle_Cell         `protobuf:"bytes,8,rep,name=squares,proto3" json:"squares,omitempty"`
	AcrossClues   []*Puzzle_Clue         `protobuf:"bytes,9,rep,name=across_clues,json=acrossClues,proto3" json:"across_clues,omitempty"`
	DownClues     []*Puzzle_Clue         `protobuf:"bytes,10,rep,name=down_clues,json=downClues,proto3" json:"down_clues,omitempty"`
	Metadata      *Puzzle_Meta           `protobuf:"bytes,11,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Puzzle) Reset() {
	*x = Puzzle{}
	mi := &file_puzzle_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Puzzle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Puzzle) ProtoMessage() {}

func (x *Puzzle) ProtoReflect() protoreflect.Message {
	mi := &file_puzzle_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Puzzle.ProtoReflect.Descriptor instead.
func (*Puzzle) Descriptor() ([]byte, []int) {
	return file_puzzle_proto_rawDescGZIP(), []int{0}
}

func (x *Puzzle) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Puzzle) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *Puzzle) GetCopyright() string {
	if x != nil {
		return x.Copyright
	}
	return ""
}

func (x *Puzzle) GetNote() string {
	if x != nil {
		return x.Note
	}
	return ""
}

func (x *Puzzle) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Puzzle) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Puzzle) GetSquares() []*Puzzle_Cell {
	if x != nil {
		return x.Squares
	}
	return nil
}

func (x *Puzzle) GetAcrossClues() []*Puzzle_Clue {
	if x != nil {
		return x.AcrossClues
	}
	return nil
}

func (x *Puzzle) GetDownClues() []*Puzzle_Clue {
	if x != nil {
		return x.DownClues
	}
	return nil
}

func (x *Puzzle) GetMetadata() *Puzzle_Meta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type PuzzleIndex struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PuzzleIndex) Reset() {
	*x = PuzzleIndex{}
	mi := &file_puzzle_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PuzzleIndex) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PuzzleIndex) ProtoMessage() {}

func (x *PuzzleIndex) ProtoReflect() protoreflect.Message {
	mi := &file_puzzle_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PuzzleIndex.ProtoReflect.Descriptor instead.
func (*PuzzleIndex) Descriptor() ([]byte, []int) {
	return file_puzzle_proto_rawDescGZIP(), []int{1}
}

func (x *PuzzleIndex) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PuzzleIndex) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *PuzzleIndex) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type Puzzle_Cell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Black         bool                   `protobuf:"varint,2,opt,name=black,proto3" json:"black,omitempty"`
	Circled       bool                   `protobuf:"varint,3,opt,name=circled,proto3" json:"circled,omitempty"`
	Fill          string                 `protobuf:"bytes,4,opt,name=fill,proto3" json:"fill,omitempty"`
	ClueAcross    int32                  `protobuf:"varint,5,opt,name=clue_across,json=clueAcross,proto3" json:"clue_across,omitempty"`
	ClueDown      int32                  `protobuf:"varint,6,opt,name=clue_down,json=clueDown,proto3" json:"clue_down,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Puzzle_Cell) Reset() {
	*x = Puzzle_Cell{}
	mi := &file_puzzle_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Puzzle_Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Puzzle_Cell) ProtoMessage() {}

func (x *Puzzle_Cell) ProtoReflect() protoreflect.Message {
	mi := &file_puzzle_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Puzzle_Cell.ProtoReflect.Descriptor instead.
func (*Puzzle_Cell) Descriptor() ([]byte, []int) {
	return file_puzzle_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Puzzle_Cell) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Puzzle_Cell) GetBlack() bool {
	if x != nil {
		return x.Black
	}
	return false
}

func (x *Puzzle_Cell) GetCircled() bool {
	if x != nil {
		return x.Circled
	}
	return false
}

func (x *Puzzle_Cell) GetFill() string {
	if x != nil {
		return x.Fill
	}
	return ""
}

func (x *Puzzle_Cell) GetClueAcross() int32 {
	if x != nil {
		return x.ClueAcross
	}
	return 0
}

func (x *Puzzle_Cell) GetClueDown() int32 {
	if x != nil {
		return x.ClueDown
	}
	return 0
}

type Puzzle_Clue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        int32                  `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Puzzle_Clue) Reset() {
	*x = Puzzle_Clue{}
	mi := &file_puzzle_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Puzzle_Clue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Puzzle_Clue) ProtoMessage() {}

func (x *Puzzle_Clue) ProtoReflect() protoreflect.Message {
	mi := &file_puzzle_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Puzzle_Clue.ProtoReflect.Descriptor instead.
func (*Puzzle_Clue) Descriptor() ([]byte, []int) {
	return file_puzzle_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Puzzle_Clue) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *Puzzle_Clue) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type Puzzle_Meta struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Created *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created,proto3" json:"created,omitempty"`
	// sha256 of the .puz file that imported to this puzzle, in
	// hex
	Sha256 string `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	// Unique ID used to refer to this puzzle
	Id string `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
	// YYYY-MM-DD parsed date that the puzzle was published, or ""
	Date          string `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Puzzle_Meta) Reset() {
	*x = Puzzle_Meta{}
	mi := &file_puzzle_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Puzzle_Meta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Puzzle_Meta) ProtoMessage() {}

func (x *Puzzle_Meta) ProtoReflect() protoreflect.Message {
	mi := &file_puzzle_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Puzzle_Meta.ProtoReflect.Descriptor instead.
func (*Puzzle_Meta) Descriptor() ([]byte, []int) {
	return file_puzzle_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Puzzle_Meta) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *Puzzle_Meta) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *Puzzle_Meta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Puzzle_Meta) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

var File_puzzle_proto protoreflect.FileDescriptor

const file_puzzle_proto_rawDesc = "" +
	"\n" +
	"\fpuzzle.proto\x12\acrossme\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb7\x05\n" +
	"\x06Puzzle\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\x02 \x01(\tR\x06author\x12\x1c\n" +
	"\tcopyright\x18\x03 \x01(\tR\tcopyright\x12\x12\n" +
	"\x04note\x18\x04 \x01(\tR\x04note\x12\x14\n" +
	"\x05width\x18\x05 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x06 \x01(\x05R\x06height\x12.\n" +
	"\asquares\x18\b \x03(\v2\x14.crossme.Puzzle.CellR\asquares\x127\n" +
	"\facross_clues\x18\t \x03(\v2\x14.crossme.Puzzle.ClueR\vacrossClues\x123\n" +
	"\n" +
	"down_clues\x18\n" +
	" \x03(\v2\x14.crossme.Puzzle.ClueR\tdownClues\x120\n" +
	"\bmetadata\x18\v \x01(\v2\x14.crossme.Puzzle.MetaR\bmetadata\x1a\xa0\x01\n" +
	"\x04Cell\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12\x14\n" +
	"\x05black\x18\x02 \x01(\bR\x05black\x12\x18\n" +
	"\acircled\x18\x03 \x01(\bR\acircled\x12\x12\n" +
	"\x04fill\x18\x04 \x01(\tR\x04fill\x12\x1f\n" +
	"\vclue_across\x18\x05 \x01(\x05R\n" +
	"clueAcross\x12\x1b\n" +
	"\tclue_down\x18\x06 \x01(\x05R\bclueDown\x1a2\n" +
	"\x04Clue\x12\x16\n" +
	"\x06number\x18\x01 \x01(\x05R\x06number\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x1ax\n" +
	"\x04Meta\x124\n" +
	"\acreated\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\x12\x0e\n" +
	"\x02id\x18\x05 \x01(\tR\x02id\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\"G\n" +
	"\vPuzzleIndex\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04dateB\x14Z\x12crossme.app/src/pbb\x06proto3"

var (
	file_puzzle_proto_rawDescOnce sync.Once
	file_puzzle_proto_rawDescData []byte
)

func file_puzzle_proto_rawDescGZIP() []byte {
	file_puzzle_proto_rawDescOnce.Do(func() {
		file_puzzle_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_puzzle_proto_rawDesc), len(file_puzzle_proto_rawDesc)))
	})
	return file_puzzle_proto_rawDescData
}

var file_puzzle_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_puzzle_proto_goTypes = []any{
	(*Puzzle)(nil),                // 0: crossme.Puzzle
	(*PuzzleIndex)(nil),           // 1: crossme.PuzzleIndex
	(*Puzzle_Cell)(nil),           // 2: crossme.Puzzle.Cell
	(*Puzzle_Clue)(nil),           // 3: crossme.Puzzle.Clue
	(*Puzzle_Meta)(nil),           // 4: crossme.Puzzle.Meta
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_puzzle_proto_depIdxs = []int32{
	2, // 0: crossme.Puzzle.squares:type_name -> crossme.Puzzle.Cell
	3, // 1: crossme.Puzzle.across_clues:type_name -> crossme.Puzzle.Clue
	3, // 2: crossme.Puzzle.down_clues:type_name -> crossme.Puzzle.Clue
	4, // 3: crossme.Puzzle.metadata:type_name -> crossme.Puzzle.Meta
	5, // 4: crossme.Puzzle.Meta.created:type_name -> google.protobuf.Timestamp
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_puzzle_proto_init() }
func file_puzzle_proto_init() {
	if File_puzzle_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_puzzle_proto_rawDesc), len(file_puzzle_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_puzzle_proto_goTypes,
		DependencyIndexes: file_puzzle_proto_depIdxs,
		MessageInfos:      file_puzzle_proto_msgTypes,
	}.Build()
	File_puzzle_proto = out.File
	file_puzzle_proto_goTypes = nil
	file_puzzle_proto_depIdxs = nil
}
