/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.crossme.Config', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.crossme.Config = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.crossme.Config, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.crossme.Config.displayName = 'proto.crossme.Config';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.crossme.Config.prototype.toObject = function(opt_includeInstance) {
  return proto.crossme.Config.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.crossme.Config} msg The msg instance to transform.
 * @return {!Object}
 */
proto.crossme.Config.toObject = function(includeInstance, msg) {
  var f, obj = {
    schemaVersion: msg.getSchemaVersion()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Creates a deep clone of this proto. No data is shared with the original.
 * @return {!proto.crossme.Config} The clone.
 */
proto.crossme.Config.prototype.cloneMessage = function() {
  return /** @type {!proto.crossme.Config} */ (jspb.Message.cloneMessage(this));
};


/**
 * optional int32 schema_version = 1;
 * @return {number}
 */
proto.crossme.Config.prototype.getSchemaVersion = function() {
  return /** @type {number} */ (jspb.Message.getFieldProto3(this, 1, 0));
};


/** @param {number} value  */
proto.crossme.Config.prototype.setSchemaVersion = function(value) {
  jspb.Message.setField(this, 1, value);
};


goog.object.extend(exports, proto.crossme);
